Workiva/w_transport

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-589
CP-590  - HTTP (client & server) Implementation  - https://github.com/Workiva/w_transport/pull/2
CP-593  - w_transport Licenses  - https://github.com/Workiva/w_transport/pull/3
CP-596  - Run code through dartfmt.  - https://github.com/Workiva/w_transport/pull/4
CP-600  - Redesign & refactor w_http API  - https://github.com/Workiva/w_transport/pull/5
CP-604  - w_transport Update description and authors.  - https://github.com/Workiva/w_transport/pull/6
CP-610  - w_transport Remove smithy  - https://github.com/Workiva/w_transport/pull/7
CP-612  - w_transport1 Enable Travis-CI  - https://github.com/Workiva/w_transport/pull/9
CP-614  - Refactor WResponse  - https://github.com/Workiva/w_transport/pull/8 …
> CP-589 Release w_transport 1.0.0

- .travis.yml
- tool/dartfmt.sh
- #33 
- Updated `dartfmt.sh` script
- Added to CI build
- n/a
- CI build passes.
> CP-698 Add dartfmt check to CI build, w_transport.

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-627
CP-631  - Allow request data to be set to null  - https://github.com/Workiva/w_transport/pull/14
CP-640  - Add pub badge w_transport  - https://github.com/Workiva/w_transport/pull/13
CP-641  - Listen for Request Cancellation in Client  - https://github.com/Workiva/w_transport/pull/15
CP-658  - Report coverage to codecov.io  - https://github.com/Workiva/w_transport/pull/17
CP-660  - Use dartanalyzer  - https://github.com/Workiva/w_transport/pull/22
CP-661  - Reorganize class elements  - https://github.com/Workiva/w_transport/pull/24
CP-663  - Use package: imports for src/ files, w_transport  - https://github.com/Workiva/w_transport/pull/25
CP-664  - Validate data type when sending, not before  - …
> CP-627 Release w_transport 1.0.1

- README.md
#57 
Move badges to new line. **Docs only change.**
n/a
n/a
@jayudey-wf
> CP-931 Move badges to separate line, w_transport

- README.md
- lib/src/http/client.dart
- lib/src/http/multipart_file.dart
- lib/src/http/requests.dart
- lib/src/web_socket/w_socket_close_event.dart
- lib/w_transport.dart
- lib/w_transport_browser.dart
- lib/w_transport_vm.dart
Resolves #49.
n/a
n/a
@jayudey-wf
> CP-1111 Revamp documentation, w_transport

- CHANGELOG.md
- Need to update changelog for 2.0.0
- Update changelog
- n/a
- n/a
@jayudey-wf
> CP-1137 Update changelog for 2.0.0, w_transport

- README.md
**DOCS ONLY CHANGE**
- Missing examples/instructions around mocking w_transport
- Add section about mocks to README
- n/a
- n/a
@jayudey-wf
> CP-1141 Add section about mocks to README, w_transport

- README.md
- lib/src/http/client.dart
- pubspec.yaml
**DOCS ONLY CHANGE**
- Update package description (fixes #82)
- Add section about `Client` to readme (fixes #86)
- Adds documentation badge to readme
@jayudey-wf
> CP-1156 Docs updates, w_transport 12.2

- lib/src/http/common/client.dart
- lib/src/http/common/multipart_request.dart
- lib/src/http/common/request.dart
- lib/src/http/http.dart
- lib/src/http/utils.dart
- lib/src/mocks/web_socket.dart
- pubspec.yaml
- `dart_style` 0.2.1 is out with improved formatting
- Apply newest formatting
- n/a
- n/a
@jayudey-wf
> CP-1165 Dart formatter updates for w_transport, dart_style 0.2.1

- lib/w_transport.dart
- lib/w_transport_vm.dart
- Fix #103 
**Source:**
- Two of the entry points have outdated library names, they've been fixed now.
**Tests:**
- n/a
- n/a
- n/a
@jayudey-wf
> CP-1249 Update entry point library names.

- CHANGELOG.md
Changelog formatting was off.
@jayudey-wf
> CP-1343 Fix formatting, changelog w_transport 2.2.0

- package.json
- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1250
CP-1255  - FormRequest documentation typo  - https://github.com/Workiva/w_transport/pull/110
CP-1337  - Add autoRetry config option for retrying timeouts  - https://github.com/Workiva/w_transport/pull/112
CP-1330  - Add option for SockJS timeout  - https://github.com/Workiva/w_transport/pull/111
CP-1343  - Fix formatting, changelog w_transport 2.2.0  - https://github.com/Workiva/w_transport/pull/113
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.1.0...CP-1250_release_2.2.0
> CP-1250 Release w_transport 2.2.0

- CHANGELOG.md
Changelog date for 2.3.0 release.
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf @jayudey-wf 
**Docs only change**.
> CP-1363 2.3.0 release date, w_transport

- package.json
- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1384
CP-1425  - Fix inheritance of autoRetry settings for requests created by Client  - https://github.com/Workiva/w_transport/pull/127
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.3.1...CP-1384_release_2.3.2
> CP-1384 Release w_transport 2.3.2

- CHANGELOG.md
> CP-1724 Update changelog for 2.4.0

- package.json
- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1426
CP-1675  - Fix mock WSocket examples in readme  - https://github.com/Workiva/w_transport/pull/135
CP-1705  - Hide dart:html.Client to avoid conflict with w_transport.Client  - https://github.com/Workiva/w_transport/pull/136
CP-1709  - FormRequest: support fields with multiple values  - https://github.com/Workiva/w_transport/pull/137
CP-1724  - Update changelog for 2.4.0  - https://github.com/Workiva/w_transport/pull/138
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.3.2...CP-1426_release_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.3.2...2.4.0
> CP-1426 Release w_transport 2.4.0

- CHANGELOG.md
**Doc change only.**
---
@jayudey-wf 
> CP-1918 Update changelog for 2.5.0

- CHANGELOG.md
**Docs change only.**
Updates the changelog for the 2.7.0 release.
@jayudey-wf 
> CP-1975 Update changelog for 2.7.0

- CHANGELOG.md
> CP-2063 Update changelog for 2.7.1 release

- CHANGELOG.md
> CP-2078 Update 2.8.0 release date

- test/unit/http/request_test.dart
_Fixes #186_ 
Our CI builds were failing intermittently due to the waits in a couple of the jitter tests being too short.
Adjust the timing of the two jitter tests to be more tolerant. We already have tests with jitter disabled that ensuring the retries are spread out as expected - the tests with jitter enabled just need to ensure that all attempts are being sent. There are additional unit tests covering the backoff (with jitter) functionality that test the utility methods directly.
@jayudey-wf 
> CP-2076 Increase duration tolerance for jitter tests

- CHANGELOG.md
> CP-2096 Update 2.9.0 release date and notes

- analysis_options.yaml
- example/http/cross_origin_file_transfer/components/download_page.dart
- example/http/cross_origin_file_transfer/components/upload_page.dart
- example/http/cross_origin_file_transfer/services/remote_files.dart
- example/web_socket/echo/client.dart
- lib/src/http/browser/multipart_request.dart
- lib/src/http/browser/request_mixin.dart
- lib/src/http/common/form_request.dart
- lib/src/http/common/multipart_request.dart
- lib/src/http/http_body.dart
- lib/src/http/http_interceptor.dart
- lib/src/http/mock/response.dart
- lib/src/http/utils.dart
- lib/src/http/vm/request_mixin.dart
- lib/src/mocks/http.dart
- lib/src/web_socket/browser/web_socket.dart
- lib/src/web_socket/common/web_socket.dart
- lib/src/web_socket/w_socket_subscription.dart
- test/integration/http/common_request/browser_test.dart
- test/integration/http/multipart_request/suite.dart
- test/integration/ws/mock_test.dart
- test/integration/ws/sockjs_test.dart
- test/unit/http/browser_utils_test.dart
- test/unit/http/client_test.dart
- test/unit/http/multipart_file_test.dart
- test/unit/http/request_test.dart
- test/unit/http/utils_test.dart
- tool/server/handlers/example/http/cross_origin_credentials_handlers.dart
- tool/server/handlers/example/http/cross_origin_file_transfer_handlers.dart
- tool/server/handlers/test/http/download.dart
- Enable strong mode for the analyzer
- Update all non-strong-mode-compliant areas
@jayudey-wf 
> CP-2619 Enable strong mode

- README.md
- docs/upgrade-guides/v3.0.0.md
Just a few more tweaks to the documentation prior to 3.0.0.
**Docs change only.**
@jayudey-wf 
> CP-2821 Documentation tweaks

- pubspec.yaml
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.4...version-bump-w_transport-3-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.4...3.0.0
> CP-2793 Release w_transport 3.0.0

- CHANGELOG.md
> CP-2849 Update release date for 3.0.0

- docs.yml
We would like this readme in the dev portal
Added docs.yml
previous major version
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp
> cp-3666 : added docs.yml

- CHANGELOG.md
Fix the wrong header for the 3.0.3 changelog.
**Docs change only.**
> WP-3986 Fix 3.0.3 changelog header

- lib/src/http/vm/request_mixin.dart
- lib/src/web_socket/common/w_socket.dart
- lib/src/web_socket/mock/w_socket.dart
- test/integration/ws/common.dart
- test/unit/ws/w_socket_subscription_test.dart
- test/unit/ws/w_socket_test.dart
> Fix failing tests

- analysis_options.yaml
- example/web_socket/echo/client.dart
- lib/src/http/common/request.dart
- lib/src/web_socket/vm/web_socket.dart
- test/integration/ws/common.dart
- test/unit/mocks/mock_web_socket_test.dart
- test/unit/ws/w_socket_subscription_test.dart
- test/unit/ws/web_socket_test.dart
We need to add lints to 3.x
Add lints to 3.x and address the lints.
> WP-4462 add close_sinks and cancel_subscriptions lints to 3.x

- pubspec.yaml
* [WP-4462 add close_sinks and cancel_subscriptions lints to 3.x](https://github.com/Workiva/w_transport/pull/275)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.4...version-bump-w_transport-3-0-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.4...3.0.5
> Release w_transport 3.0.5

- CODEOWNERS
Add a `CODEOWNERS` file so that we can turn on the "require reviews from codeowners" option.
> WP-5627 Add CODEOWNERS file

- pubspec.yaml
* [WP-5850 Use hasProperty to detect sockjs.js](https://github.com/Workiva/w_transport/pull/299)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.0...Workiva:release_w_transport_3_2_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.0...3.2.1
> WP-5726 Release w_transport 3.2.1

- CHANGELOG.md
Add changelog entries for 3.2.2 and 3.2.3 (about to be released).
> WP-6541 Changelog for 3.2.2 and 3.2.3

- .gitignore
- .travis.yml
- analysis_options.yaml
- example/common/global_example_menu.dart
- example/common/global_example_menu_component.dart
- example/common/typedefs.dart
- example/http/cross_origin_credentials/client.dart
- example/http/cross_origin_credentials/index.html
- example/http/cross_origin_file_transfer/client.dart
- example/http/cross_origin_file_transfer/components/app_component.dart
- example/http/cross_origin_file_transfer/components/download_page.dart
- example/http/cross_origin_file_transfer/components/drop_zone_component.dart
- example/http/cross_origin_file_transfer/components/file_transfer_list_component.dart
- example/http/cross_origin_file_transfer/components/file_transfer_list_item_component.dart
- example/http/cross_origin_file_transfer/components/upload_page.dart
- example/http/cross_origin_file_transfer/index.html
- example/http/simple_client/client.dart
- example/http/simple_client/index.html
- example/index.dart
- example/index.html
- example/style.css
- example/web_socket/echo/client.dart
- example/web_socket/echo/index.html
- pubspec.yaml
- test/unit/http/browser_utils_test.dart
Pretty self-explanatory.
@evanweible-wf
> AF-326 Bump outdated lower bounds

- CHANGELOG.md
Forgot to add a changelog entry for #317.
No need to release after this is merged, just wanted to get it updated so that the next release includes this.
> AF-1711 Update changelog for v3.2.6

- example/pubspec.yaml
- example/web/common/global_example_menu_component.dart
- example/web/http/cross_origin_file_transfer/components/app_component.dart
- example/web/http/cross_origin_file_transfer/components/download_page.dart
- example/web/http/cross_origin_file_transfer/components/drop_zone_component.dart
- example/web/http/cross_origin_file_transfer/components/file_transfer_list_component.dart
- example/web/http/cross_origin_file_transfer/components/file_transfer_list_item_component.dart
- example/web/http/cross_origin_file_transfer/components/upload_page.dart
A few more codemod changes.
@corwinsheahan-wf @sebastianmalysa-wf
> AF-3768 Update over_react component boilerplate for Dart 1 & 2 compatibility (pt2)

- LICENSE
- lib/src/http/auto_retry.dart
- lib/src/http/common/request.dart
- lib/src/http/utils.dart
- test/unit/http/utils_test.dart
The jitter approach used previously for exponential backoffs still leads to peaks in server load. This can be improved by adopting a more advanced algorithm from Polly: https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry#new-jitter-recommendation
Implements the above algorithm in Dart, and uses it by default with the exponential backoff.
[contributing-manual-testing]: https://github.com/Workiva/w_transport/blob/master/CONTRIBUTING.md#manual-tes …
> CPLAT-10079: Use advanced jitter algorithm

- lib/src/http/utils.dart
- lib/w_transport.dart
It would be useful for internal downstream consumers to have access to the advanced jitter backoff calculation.
Expose the advanced jitter backoff calculator, and generalize parameters for other usages.
> CPLAT-11599: Expose advanced jitter

- .gitignore
- skynet.py
- skynet.yaml
Currently release pipelines are stopping at the verify QA step because it doesn't have a skynet.yaml which means we have to manually get the pipeline past that step but we don't want to run the tests that are already being run inside of github actions.
Add a script that gets the results of the github actions and and either passes or fails the skynet config depending on the results.
Add skynet config that verifies github actions run passes. …
> fw-59 Add skynet config with github actions check

- skynet.yaml
Update to latest version of the github ci verifier image that fixes the rate limit issue.
Update to latest image of the github ci verifier.
Update to latest image of the github ci verifier.
> FW-174 Update skynet image to latest github ci verifier

- pubspec.yaml
* [Fix JSON decoding when charset isn't specified on VM to use UTF-8](https://github.com/Workiva/w_transport/pull/376)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/4.1.2...Workiva:release_w_transport_4.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/4.1.2...4.1.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=377)
> RM-152361 Release w_transport 4.1.3

- pubspec.yaml
* [Mockito 5](https://github.com/Workiva/w_transport/pull/381)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/4.1.4...Workiva:release_w_transport_4.1.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/4.1.4...4.1.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=382)
> RM-165920 Release w_transport 4.1.5

- pubspec.yaml
* Major changes:
* [FEDX-60 : Updated Null safety](https://github.com/Workiva/w_transport/pull/397)
* [Update changelog](https://github.com/Workiva/w_transport/pull/402)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/4.1.6...Workiva:release_w_transport_5.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/4.1.6...5.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_ …
> RM-190883 Release w_transport 5.0.0

- pubspec.yaml
* [Nullable fixes](https://github.com/Workiva/w_transport/pull/404)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.0.0...Workiva:release_w_transport_5.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.0.0...5.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=406)
> RM-208795 Release w_transport 5.0.1

- CHANGELOG.md
> Add changelog entry for 5.1.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/dart_ci.yaml
- _test_server/lib/src/handlers/test/http/reflect_handler.dart
- lib/src/http/mock/request_mixin.dart
- lib/src/http/utils.dart
- lib/src/mocks/mock_http.dart
- test/integration/platforms/browser_transport_platform_test.dart
- test/unit/http/client_test.dart
- test/unit/http/request_test.dart
- test/unit/mocks/mock_http_test.dart
Master CI was failing on some nnbd errors
Fixes those nnbd errors and updates gha process to run on the latest boilerplate
> FEA-3269: Fixed CI and addressed NNBD errors

- _test_server/analysis_options.yaml
- analysis_options.yaml
- example/analysis_options.yaml
This PR bumps/adds workiva_analysis_options to v2. This is being done in an effort to adopt consistency in
`analysis_options.yaml` files across the codebase, and ensure all developers are using the most up to date
functionality that the dart analyzer can provide.
Failing CI will be evaluated by someone from FEDX and resolved. We will reach out when the pr is ready for review.
If you have any questions, concerns, or opinions, please reach out to #support-frontend-dx.
[_Created by Sourcegraph batch change `Workiva/workiva_analysis_options_v2`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/workiva_analysis_options_v2)
> Workiva Analysis Options v2
