.travis.yml
README.md

- Now that w_transport is public, we need to enable Travis-CI.
**Source:**
- Add `.travis.yml`
- Add build status badge to readme.
**Tests:**
- n/a
- n/a
- Travis-CI should pass and show up on this PR
- Badge should be visible on the readme

CP-612 w_transport Enable Travis-CI

---

example/http/cross_origin_credentials/service.dart
example/http/cross_origin_file_transfer/services/remote_files.dart
example/http/simple_client/client.dart
lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
lib/src/http/w_http_common.dart
lib/src/http/w_http_server.dart
test/w_http_client_integration_test.dart
test/w_http_client_test.dart
test/w_http_common_integration_tests.dart
test/w_http_server_integration_test.dart
test/w_http_server_test.dart
tool/server/proxy.dart

- Need to be able to update/replace the data source on a `WResponse` instance
- Need to be able to access response data multiple times
- Should always try to decode response data
**Source:**
- Refactor `WResponse` such that all data access paths are based off of a single data source stream that can be updated and accessed multiple times.
- Add a caching stream transformer
- Add a getter for the single data source stream that returns original source stream on first access and then a new stream from the cached response on subsequent accesses
- Add an `update()` method for replacing the stream (will invalidate cache)
- Change simple data access property getters to be methods to make it more apparent that they are async
- `data` --> `asFuture()`
- `text` --> `asText()`
- `stream` --> …

CP-614 Refactor WResponse

---

lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
lib/src/http/w_http_server.dart
test/utils.dart
test/w_http_common_integration_tests.dart
test/w_http_common_test.dart
tool/coverage.sh

There are certain scenarios where multiple consumers will be working with a single request, and in those scenarios there is currently no way to be made aware of a request cancellation. Only the consumers who cancels the request will be aware of that action.
**Source:**
- Check for cancellation before opening request, before sending request, and before delivering the response.
- Cause a request failure by throwing an exception if a cancellation was detected (this replaces the previous behavior of just never completing the request).
- `WHttpException` modified slightly to account for a null request.
- Did some reordering/alphabetizing in the `WRequest` class
**Tests:**
- Tests updated
- New test added to verify a cancellation causes a failure
- Request cancellation
- Tests pass
- Examples …

CP-618 Make request cancellations cause failure (throw error)

---

README.md
example/common/global_example_menu_component.dart
example/http/cross_origin_credentials/dom.dart
example/http/cross_origin_credentials/service.dart
example/http/cross_origin_file_transfer/components/download_page.dart
example/http/cross_origin_file_transfer/services/file_transfer.dart
example/http/cross_origin_file_transfer/services/remote_files.dart
example/http/simple_client/client.dart
lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
lib/src/http/w_http_common.dart
lib/src/http/w_http_server.dart
lib/w_transport.dart
test/utils.dart
test/w_http_client_integration_test.dart
test/w_http_client_test.dart
test/w_http_common_integration_tests.dart
test/w_http_common_test.dart
test/w_http_server_integration_test.dart
test/w_http_server_test.dart
tool/server/proxy.dart

Originally I created a `w_transport/w_http.dart` entry point that I intended to be separate from the socket one, but with Dart's tree-shaking that's an anti-pattern. Instead, everything should be consolidated into a single self-named entry point.
**Source:**
- Rename `w_transport/w_http.dart` entry point to `w_transport/w_transport.dart`
- Update imports
- Update docs/comments
**Tests:**
- Update imports
- Everything (main import changed)
- Tests should pass
- Examples should still run as expected

CP-623 Change entry point to w_transport

---

lib/src/http/w_http_client.dart
lib/src/http/w_http_server.dart
test/w_http_client_test.dart
test/w_http_server_test.dart
tool/coverage.sh

- An `ArgumentError` is thrown when trying to set a `WRequest`'s data to null.
**Source:**
- Update the data validation methods to allow null data.
**Tests:**
- 2 new tests added to cover that scenario
**Additional Changes:**
- Fixed the `coverage.sh` script (bad copy paste)
- Setting data on `WRequest`
- All tests pass

CP-631 Allow request data to be set to null

---

README.md

- w_transport is on Pub now, so we should add the Pub badge.
**Source:**
- Add pub badge to readme
**Tests:**
- n/a
- n/a
- Pub badge shows up on readme with `v1.0.0`
- Pub badge links to pub.dartlang.org/packages/w_transport

CP-640 Add pub badge w_transport

---

example/http/cross_origin_file_transfer/services/file_transfer.dart
lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
test/w_http_client_test.dart
tool/server/proxy.dart

- Request cancellation should cause the request to fail (throw an error async) in all scenarios. Currently, this works if the request is cancelled before being sent or after the response has been returned. If request cancellation occurs while the request is open, the request is cancelled but it does not result in an error being thrown.
**Source:**
- Listen to `request.onAbort` in the client implementation to capture request cancellation while the request is open and throw a `WHttpException`.
**Tests:**
- One test updated, examples updated to utilize this new behavior.
- Request cancellation.
- Tests pass.
- In the File Transfer example, verify that canceling an upload and canceling a download still triggers the visual feedback (red background) that it did before. Previously, the visual …

CP-641 Listen for Request Cancellation in Client

---

.travis.yml
README.md
pubspec.yaml
test/run_tests.dart

- We need to generate and report code coverage to codecov.io
**Source:**
- n/a
**Tools:**
- Update test script to allow an option for only generating .lcov file
- Update travis.yml to generate and report code coverage
**Tests:**
- [List/summary of changes to tests, addition of examples, etc]
**Other:**
- Add codecov badge to readme.
- n/a
- Coverage badge should be visible on README (will report "unknown" coverage until merged)
- Travis-ci should pass and this output should be visible in the logs towards the bottom:
```
The command "pub run dart_codecov_generator --report-on=lib/ --no-html --verbose" exited with 0.
pub run dart_codecov coverage.lcov
Running dart_codecov...
Coverage sent to codecov.io successfully.
```
@jayudey-wf

CP-658 Report coverage to codecov.io

---

.travis.yml
tool/analyze.sh

- We're not using dartanalyzer
**Source:**
- n/a
**Tests:**
- n/a
**Tools:**
- Added a `analyze.sh` tool that runs the dartanalyzer
- n/a
- Travis-CI passes and the dartanalyzer output can be found at the end of the build logs
```
$ ./tool/analyze.sh
Analyzing [lib/fluri.dart, test/fluri_test.dart]...
No issues found
No issues found
```

CP-660 Use dartanalyzer

---

lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
test/w_http_client_test.dart
test/w_http_server_test.dart
tool/server/proxy.dart

- #19 
- In an effort to be organized and consistent, the elements in a class should follow this order:
- static variables
- static methods
- public variables
- private variables
- constructors (main first, named next, private named last)
- public methods
- private methods
**Source:**
- Reorganize all the classes
- Add some missing documentation on private elements
**Tests:**
- n/a
- n/a
- Travis-CI passes.

CP-661 Reorganize class elements

---

lib/src/http/w_http.dart
lib/src/http/w_http_client.dart
lib/src/http/w_http_common.dart
lib/src/http/w_http_server.dart
lib/w_transport.dart
lib/w_transport_client.dart
lib/w_transport_server.dart
test/w_http_client_test.dart
test/w_http_server_test.dart
tool/server/proxy.dart

- #25 
- https://twitter.com/sethladd/status/603641186826477568
- It's recommended to use `package:` imports instead of relative imports
**Source:**
- Update imports to use `package:` syntax whenever possible
**Tests:**
- n/a
- n/a
- Travis-CI passes.

CP-663 Use package: imports for src/ files, w_transport

---

lib/src/http/w_http.dart
test/w_http_server_integration_test.dart

- We should not immediately validate the data type; should validate it just before sending, instead.
- Without this change, it's not possible to set an intermediate version of a data payload (like w_service does) that may eventually get transformed into a valid data type
**Source:**
- Move the data type validation step from the setter of the `data` property to the `_send` method. This allows the data to be set to anything, but only valid data types will actually be sent. Invalid data types will still throw an exception, just a bit later.
**Tests:**
- Tests updated.
- Request data payload type validation
- Tests pass.

CP-664 Validate data type when sending, not before

---

example/http/cross_origin_file_transfer/components/download_page.dart
example/http/cross_origin_file_transfer/components/drop_zone_component.dart
example/http/cross_origin_file_transfer/components/file_transfer_list_item_component.dart
example/http/cross_origin_file_transfer/services/file_transfer.dart
lib/src/http/w_http.dart
test/w_http_common_integration_tests.dart

- #27 
**Source:**
- Changed all instances of `cancelled` to `canceled`
**Tests:**
- Changed all instances of `cancelled` to `canceled`
- n/a
- Smithy passes.
- Example still works as expected.

CP-685 cancelled --> canceled, w_transport

---

test/w_http_client_test.dart
test/w_http_common_test.dart
test/w_http_server_test.dart
tool/analyze.sh

- #28 
- Dart analyzer tool already existed and was in the CI build, but it should also include the test/ directory.
**Source:**
- n/a
**Tests:**
- Added the `noSuchMethod` implementation to all Mock classes to calm the compiler.
- n/a
- CI build passes.

CP-688 Use dart analyzer on test directory.

---

lib/src/http/w_http.dart
test/w_http_common_test.dart

- If you try to construct a `WHttp` instance before setting the configuration, you will receive a non-helpful exception instead of the descriptive "w_transport configuration must be set.." error.
- #35 
**Source:**
- Add a check to the `WHttp` constructor before initializing.
**Tests:**
- Add a test to verify this use case.
- n/a
- CI build passes.

CP-702 Verify config is set before constructing WHttp

---

.travis.yml
pubspec.yaml

- Still waiting on https://github.com/dart-lang/coverage/pull/67
- Temporarily remove the code coverage dependencies so that we can cut a release.
- n/a
- CI build passes.

CP-714 Temporarily remove code coverage dependencies, w_transport

---

CHANGELOG.md

- #20 
- We need a changelog file, especially since it's displayed on pub.dartlang.org
> Documentation only change
- Added `CHANGELOG.md`
@jayudey-wf 
---
I will keep this open until we're ready for the next release, at which point I'll finalize updates and get one last round of reviews. After that's merged and the release is cut, I'll reopen and repeat the process.

CP-671 Add changelog, w_transport

---

pubspec.yaml
tool/dartium.sh

- #39 
- Add a Dart SDK constraint to pubspec.yaml.
- Also allows use to use the `^` syntax for dependencies
- Removed `dartium.sh` tool because it wasn't really useful.
- n/a
- `pub publish --dry-run` shows no warnings

CP-751 Add SDK constraint, w_transport

---

test/run_tests.dart

- When using the test script if you have multiple versions of dartium installed you will get failed results when running the integration tests.
**Source:**
- Updated test runner to use content shell
**Tests:**
- n/a
- the test.sh script
- run the test.sh script to ensure that it's still working
@evanweible-wf

CP-754 Update tests to run with content shell instead of dartium

---

example/http/cross_origin_file_transfer/components/download_page.dart

- When running dartium in checked mode the cross origin file transfer example errors due to a typing mis-match.
**Source:**
- Update types
**Tests:**
- Change is to an example and not source code
- N/A
- Run the affected example in checked mode and review the console for no errors.
@evanweible-wf

Updating typing in download_page.dart

---

README.md

#55 - forgot to add a section to the readme about dev when updating w_transport to use dart_dev.
Add "development" section to readme.
n/a
n/a
@jayudey-wf

CP-930 Add "Development" section to readme, w_transport

---

lib/src/http/browser/client.dart
lib/src/http/client.dart
lib/src/http/common/client.dart
lib/src/http/mock/client.dart
lib/src/http/vm/client.dart
lib/src/mocks/http.dart
test/unit/http/client_test.dart

- To reduce repetition (and to make `Client` more useful), you should be able to set headers and the `withCredentials` flag on a `Client` and have those applied to all requests created by that client.
**Source:**
- Add `headers` and `withCredentials` getters/setters to `Client`
- Apply values to all requests created by `Client`
**Tests:**
- Unit tests added to verify this `Client` behavior
- n/a, new functionality
- CI passes
@jayudey-wf

CP-1089 Allow headers, withCredentials to be set on Client

---

lib/src/http/browser/request_mixin.dart
lib/src/http/http.dart
test/integration/http/http_static/suite.dart

Resolves #73 
**Source:**
- Add streamed variants of the request methods on the `Http` class to make it easy to get a streamed response for simple requests.
- Bug fix: the browser implementation of streamed response was not constructing the byte stream correctly
**Tests:**
- Integration tests added
- n/a
- CI passes
@jayudey-wf

CP-1113 Add stream static methods to Http

---

.travis.yml
README.md
lib/src/browser_adapter.dart
lib/src/web_socket/browser/sockjs.dart
lib/src/web_socket/common/w_socket.dart
lib/w_transport_browser.dart
package.json
pubspec.yaml
test/integration/browser_integration_test.dart
test/integration/ws/common.dart
test/integration/ws/sockjs_test.dart
test/naming.dart
tool/dev.dart
tool/server/sockjs.js

Resolves #68.
- Not all browsers support native WebSockets. SockJS provides the ability to fallback to XHR-streaming if this is the case, but currently w_transport is not compatible with SockJS.
**Source:**
- Add an additional implementation of the `WSocket` class that utilizes [SockJS client](https://github.com/Workiva/sockjs-dart-client) instead of the native `WebSocket` class directly.
- This is almost identical to the browser implementation (in fact I may try to merge some of the common code)
- Add optional parameters to the `configureWTransportForBrowser()` method for enabling SockJS.
To use SockJS in the browser:
```dart
import 'package:w_transport/w_transport.dart';
import 'package:w_transport/w_transport_browser.dart';
main() async {
configureWTransportForBrowser(useSockJS: true, …
```

CP-1106 Support usage of SockJS, w_transport.

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-716
CP-751  - Add SDK constraint, w_transport  - https://github.com/Workiva/w_transport/pull/42
CP-754  - Update tests to run with content shell instead of dartium  - https://github.com/Workiva/w_transport/pull/43
CP-819  - Refactor internal source code organization  - https://github.com/Workiva/w_transport/pull/51
CP-830  - Updating typing in download_page.dart  - https://github.com/Workiva/w_transport/pull/52
CP-871  - Utilize dart_dev for tooling, refactor server component  - https://github.com/Workiva/w_transport/pull/53
CP-884  - Ensure license is applied to all source files, w_transport  - https://github.com/Workiva/w_transport/pull/54
CP-930 Add "Development" section to readme, w_transport - …

CP-716 Release w_transport 2.0.0

---

pubspec.yaml

- We are targeting a branch of the `sockjs-dart-client` repo
- Target the 0.3.0 release of `sockjs-dart-client`
- n/a
- n/a
@jayudey-wf

CP-1147 Target sockjs-dart-client release 0.3.0

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1142
CP-1147  - Target sockjs-dart-client release 0.3.0  - https://github.com/Workiva/w_transport/pull/83
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.0.0...CP-1142_release_2.0.1

CP-1142 Release w_transport 2.0.1

---

README.md
lib/src/http/base_request.dart
lib/src/http/client.dart
lib/src/http/common/client.dart
lib/src/http/common/request.dart
lib/src/http/request_exception.dart
test/integration/http/common_request/suite.dart
test/unit/http/client_test.dart
test/unit/http/request_test.dart

- Missing support for setting an explicit timeout threshold on HTTP requests.
**Source:**
- `BaseRequest` now includes a `timeoutThreshold` property of type `Duration`
- `timeoutThreshold = null` means no threshold is enforced
- Prior to sending a request, a timer will be set that will cancel the request if it doesn't complete within the threshold
- `Client` now includes a `timeoutThreshold` property that serves as the default value for all requests created from a `Client` instance
- Example error message from a request timeout:
```
RequestException: GET /test
TimeoutException after 0:00:00.500000: Request took too long to complete.
```
**Tests:**
- Unit tests and integration tests added to ensure that
- timeout threshold is not enforced if not set
- timeout threshold does nothing if …

CP-1154 HTTP: support timeout threshold.

---

CHANGELOG.md
lib/src/http/client.dart
lib/src/http/common/client.dart
pubspec.yaml
test/unit/http/client_test.dart

Resolves #91.
- #91 `Client` should have a `baseUri` that all requests inherit
**Source:**
- Bumped version of Fluri to be at least 1.1.0 since [new URI methods](https://github.com/Workiva/fluri/blob/master/CHANGELOG.md#110) were added with the intent that they would be used to build off of a base URI.
- Add `baseUri` to `Client` abstract and `CommonClient` implementation
- Requests created by a client now inherit this `baseUri`
**Tests:**
- Unit test added to test that each type of request properly inherits the base URI
- n/a
- CI passes.
@jayudey-wf

CP-1179 Add a `baseUri` field to `Client`

---

CHANGELOG.md
README.md
lib/src/http/base_request.dart
lib/src/http/client.dart
lib/src/http/common/client.dart
lib/src/http/common/request.dart
lib/src/http/http_interceptor.dart
lib/w_transport.dart
test/unit/http/client_test.dart
test/unit/http/http_interceptor_test.dart
test/unit/http/request_test.dart
test/unit/platform_independent_unit_test.dart

- To support more advanced functionality in an http `Client`, we need a way to intercept requests right before dispatch and responses right before delivery.
**Source:**
- Add a `requestInterceptor` field to `BaseRequest` that, if set, will be applied right before dispatching the request.
- Signature:
```
Future<Null> RequestInterceptor(BaseRequest request)
```
- Add a `responseInterceptor` field to `BaseRequest` that, if set, will be applied right after the response is received but before it's delivered to the caller.
- Signature:
```
Future<BaseResponse> ResponseInterceptor(
FinalizedRequest request, BaseResponse response,
[RequestException error])
```
- Add a `Pathway<T>` class that defines a path on which a payload of type `T` travels and on which interceptors can be registered.
- Add …

CP-1177 Support request, response interception

---

CHANGELOG.md
lib/src/http/common/request.dart
test/unit/http/request_test.dart

_Fixes #96_
- #96 Headers passed to any of the request dispatch methods (`.get()`, `.post()`, etc) are incorrectly ignored.
**Source:**
- If headers are given to a dispatch method, merge them with existing headers on the request (if any).
**Tests:**
- Unit tests added for each request dispatcher as well as one for testing the merging of headers.
- n/a
- CI passes
@jayudey-wf

CP-1202 Bug fix: dont ignore headers passed to dispatch methods

---

CHANGELOG.md
README.md
lib/src/browser_adapter.dart
lib/src/mock_adapter.dart
lib/src/platform_adapter.dart
lib/src/vm_adapter.dart
lib/src/web_socket/w_socket.dart
lib/w_transport_browser.dart
test/integration/ws/common.dart
test/integration/ws/sockjs_test.dart
test/naming.dart

- Configuring SockJS usage on a global basis will not work in two scenarios:
- application with mixed usage of native websockets and SockJS
- application where `configureWTransportForBrowser()` is called more than once (last config will win, which could break some usages)
**Source:**
- Deprecate the method for applying SockJS config on a global basis (via `configureWTransportForBrowser()`)
- Add the SockJS optional params to the `WSocket.connect()` method (will be ignored on the server for now)
**Tests:**
- Current test suite still passes (although the deprecation warnings show)
- **TODO:**
- WebSocket connection when configured with SockJS
- CI passes
@jayudey-wf

CP-1247 Move sockjs config to be per-socket.

---

CHANGELOG.md
lib/src/http/mock/response.dart
lib/src/http/response.dart
test/unit/http/response_test.dart
test/unit/mocks/mock_response_test.dart

Fix #93.
This allows the consumer to create new `Response` and `StreamedResponse` objects from an existing instance when they only want to modify one or a few of its fields.
**Source:**
- Add new `replace()` method to `Response` and `StreamedResponse`
**Tests:**
- Add test for new `replace()` method on `Response`
- Add test for new `replace()` method on `StreamedResponse`
- None, new API
- New tests sufficiently test new functionality
- CI passes
@evanweible-wf 
FYI @jayudey-wf

CP-1243 Add Response.replace() and StreamedResponse.replace()

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1150
CP-1156  - Docs updates, w_transport 12.2  - https://github.com/Workiva/w_transport/pull/87
CP-1154  - HTTP: support timeout threshold.  - https://github.com/Workiva/w_transport/pull/85
CP-1160  - Remove old mock file.  - https://github.com/Workiva/w_transport/pull/88
CP-1165  - Dart formatter updates for w_transport, dart_style 0.2.1  - https://github.com/Workiva/w_transport/pull/90
CP-1179  - Add a `baseUri` field to `Client`  - https://github.com/Workiva/w_transport/pull/94
CP-1177  - Support request, response interception  - https://github.com/Workiva/w_transport/pull/92
CP-1202  - Bug fix: dont ignore headers passed to dispatch methods  - https://github.com/Workiva/w_transport/pull/101
CP-1186 …

CP-1150 Release w_transport 2.1.0

---

README.md
lib/src/http/requests.dart

- Typo in the readme and in the docstrings for `FormRequest` - `body` should be `fields` (thanks @christopherdaly-wf!)
**Source:**
- Update readme and doc string
**Tests:**
- N/a
- N/a
- N/a
@jayudey-wf

CP-1255 FormRequest documentation typo

---

CHANGELOG.md
lib/src/http/auto_retry.dart
lib/src/http/common/request.dart
test/unit/http/request_test.dart

- Currently there's no way for requests that fail due to exceeding the timeout threshold to be retried.
**Source:**
- Add an `autoRetry.forTimeouts` flag that defaults to `true` and determines whether or not a timed out request will be retried.
**Tests:**
- 2 unit tests added
- Request sending and retry logic.
- CI Passes.
@jayudey-wf 
fyi: @trentonsmith-wf @richklein-wf (this will be used in w_session to fix the session context retry issue)

CP-1337 Add autoRetry config option for retrying timeouts

---

CHANGELOG.md
example/web_socket/echo/client.dart
example/web_socket/echo/index.html
lib/src/browser_adapter.dart
lib/src/mock_adapter.dart
lib/src/platform_adapter.dart
lib/src/vm_adapter.dart
lib/src/web_socket/browser/sockjs.dart
lib/src/web_socket/w_socket.dart
tool/dev.dart
tool/server/sockjs.js

There's currently no way to configure the timeout option for the underlying sockjs-client-dart library. If a socket (using SockJS) takes too long to connect, the connection will be canceled. This is problematic for slower network connections.
**Source:**
- Expose the underlying SockJS timeout option via a `sockJSTimeout` optional param.
**Tests:**
- The only way to test this would be an integration test with a custom sockjs server that holds the WS negotiation or maybe the info request until the timeout expires. I'm not sure exactly how to do this, but I can look into if we think it's necessary.
- SockJS socket connection.
- CI passes.
- Open the Echo example and check "Use SockJS" along with at least one of "SockJS websocket" and "SockJS xhr-streaming". Should connect and echo as …

CP-1330 Add option for SockJS timeout

---

CHANGELOG.md
lib/src/http/auto_retry.dart
lib/src/http/common/request.dart
lib/w_transport.dart
test/unit/http/request_test.dart

Fix #102.
- No support for retry back-off
**Source:**
- Add a `RetryBackOff` class to represent the type of back-off and base duration.
- Add a `backOff` option to the auto retry config class
- Add logic to delay retries according to the configured back-off
**Tests:**
- Tests added for `none`, `fixed`, and `exponential` back-off.
- Request retrying
- CI passes.
@jayudey-wf

CP-1350 Retry back-off, w_transport.

---

CHANGELOG.md
lib/src/http/common/request.dart
lib/src/http/request_exception.dart
test/unit/http/request_exception_test.dart
test/unit/http/request_test.dart

Fix #100.
- Error messaging around request failures could be improved, especially when retries are involved.
**Source:**
- More robust `toString()` implementation for `RequestException` that takes into account retries
- Before:
```
RequestException: GET 400 BAD REQUEST https://example.com/
```
- After:
```
RequestException: GET https://example.com/
Attempt #1: 400 BAD REQUEST
Attempt #2: 403 FORBIDDEN
Attempt #3: 500 INTERNAL SERVER ERROR
Attempt #4: (TimeoutException after 0:00:00.100000: Request took too long to complete.)
Attempt #5: (Exception: Unexpected failure.)
```
**Tests:**
- Tests added.
- n/a
- CI passes.
@jayudey-wf

CP-1356 Improve error messaging around failed requests, w_transport.

---

CHANGELOG.md
lib/src/http/base_request.dart
lib/src/http/common/request.dart
test/unit/http/request_test.dart

Fix #104.
- There are corner cases where being able to manually retry a request after a failure would be useful (in particular, w_session membership preferences request)
**Source:**
- Add a `.retry()` and `.streamRetry()` methods to `BaseRequest` that allow manual retrying of requests that have already been attempted and have failed. They will throw a `StateError` if the request has not yet been sent, if it is still in progress, or if it completed successfully.
**Tests:**
- Unit tests added.
- n/a
- CI passes.
@jayudey-wf

CP-1359 Manual request retrying

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1344
CP-1350  - Retry back-off, w_transport.  - https://github.com/Workiva/w_transport/pull/115
CP-1356  - Improve error messaging around failed requests, w_transport.  - https://github.com/Workiva/w_transport/pull/117
CP-1359  - Manual request retrying  - https://github.com/Workiva/w_transport/pull/118
CP-1363  - 2.3.0 release date, w_transport  - https://github.com/Workiva/w_transport/pull/119
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.2.0...CP-1344_release_2.3.0

CP-1344 Release w_transport 2.3.0

---

lib/src/http/common/request.dart

- In non-dartium browsers (where dart is compiled to JS), a very weird situation can occur that results in `response` being assigned a completely incorrect value. I'm assuming this is a dart2js bug and will try to get a reduced test case created later.
**Source:**
- Through debugging, I discovered that adding a print statement at a certain line that referenced the `response` variable that was being assigned an incorrect value actually fixed the issue.
- Instead of a logging statement, inserting a no-op assignment of the `response` variable to null accomplishes the same thing.
**Tests:**
- No idea how to test this.
- n/a
- Open the w_session example *in Chrome*
- Log in once to establish a session
- Reload
- Using the Network Link Conditioner, turn on a 10 second downlink delay
- Try to …

CP-1382 Workaround for dart2js bug when request is canceled.

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1364
CP-1382  - Workaround for dart2js bug when request is canceled.  - https://github.com/Workiva/w_transport/pull/122
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.3.0...CP-1364_release_2.3.1

CP-1364 Release w_transport 2.3.1

---

CHANGELOG.md
lib/src/http/common/client.dart
test/unit/http/client_test.dart

Fix #126.
There are three `autoRetry` settings that do not get properly passed down to requests created by a `Client` instance.
**Source:**
- Copy `autoRetry.backOff`, `autoRetry.forTimeouts`, and `autoRetry.maxRetries` to requests created by a `Client`
**Tests:**
- Unit test added.
- n/a
- CI passes.
@jayudey-wf 
fyi: @jeroencranendonk-wf

CP-1425 Fix inheritance of autoRetry settings for requests created by Client

---

README.md

@stevenosborne-wf pointed out that the examples for mocking WSocket instances in the readme are incorrect.
Fix them. **Documentation only change.**
@jayudey-wf

CP-1675 Fix mock WSocket examples in readme

---

CHANGELOG.md
lib/src/http/browser/multipart_request.dart

Dart 1.16 exposes a new `Client` class in the `dart:html` library. This conflicts with the `Client` class in w_transport. Thanks for pointing this out @theisensanders-wf.
To avoid this, I'm hiding the `Client` class form the `dart:html` import in the one file that this conflict occurs. **This will work for now, but we should probably consider renaming our class since consumers will likely hit this conflict with their own imports.**
@jayudey-wf

CP-1705 Hide dart:html.Client to avoid conflict with w_transport.Client

---

CHANGELOG.md
lib/src/http/browser/multipart_request.dart
lib/src/http/common/form_request.dart
lib/src/http/requests.dart
lib/src/http/utils.dart
test/integration/http/form_request/suite.dart

_Dependent on #136._
Most servers support form requests with multiple-value fields. For example:
```
?foo=bar&foo=baz
```
The above query string would produce this form payload:
```
{ foo: ['bar', 'baz'] }
```
Currently, we don't support this because the `fields` map is of type `Map<String, String>`.
- Change the signatures of the `FormRequest.fields` getters and setters to `Map<String, dynamic>`
- Update the utilities for converting from map to query string and vice versa to support fields with multiple values
- Add type checks to verify that each field's value is either `String` or `Iterable<String>`
- Add test to exercise sending a field with multiple values
- Add test to verify that invalid field value type causes an `ArgumentError` to be thrown …

CP-1709 FormRequest: support fields with multiple values

---

pubspec.yaml

sockjs-dart-client version 0.3.1 was released with a bug fix, but we haven't yet updated our dependency to point to that version.
Point to sockjs-dart-client 0.3.1
@jayudey-wf 
fyi: @dominicfrost-wf

CP-1862 Upgrade to sockjs-dart-client 0.3.1

---

codecov.yml
pubspec.yaml

Coverage should be working with the latest Dart SDK release (1.17.0) and at least `coverage` 0.7.4. Additionally, codecov.io made a change that now requires configuration to be set in a `codecov.yml` file instead of through their UI. This is why code coverage comments and the CI status check have not been appearing on recent PRs.
Upgrade to `coverage ^0.7.4` and add a `codecov.yml`.
@jayudey-wf 

CP-1884 Fix Coverage, w_transport

---

CHANGELOG.md
lib/src/mocks/http.dart
lib/src/web_socket/browser/sockjs.dart
lib/src/web_socket/browser/w_socket.dart
lib/src/web_socket/common/w_socket.dart
lib/src/web_socket/mock/w_socket.dart
lib/src/web_socket/vm/w_socket.dart
lib/src/web_socket/w_socket_close_event.dart
lib/src/web_socket/w_socket_subscription.dart
test/integration/ws/common.dart
test/integration/ws/mock_test.dart
test/unit/platform_independent_unit_test.dart
test/unit/ws/w_socket_subscription_test.dart
test/unit/ws/w_socket_test.dart
test/utils.dart
tool/dev.dart

_Fixes #134._
- `WSocket` extends `Stream` and `StreamSink`, but was not fulfilling those contracts in all scenarios. In particular:
- After obtaining a `StreamSubscription` instance from a call to `WSocket.listen()`, reassigning the `onData()`, `onError()`, and `onDone()` handlers had no effect.
```dart
var webSocket = await WSocket.connect(...);
var subscription = webSocket.listen((data) { ... });
// This does nothing:
subscription.onData((data) { ... });
// Same goes for onError() and onDone()
```
- A subscription to a `WSocket` instance did not properly respect pause and resume signals. This could produce a memory leak by buffering WebSocket events indefinitely.
- A `WSocket` instance was immediately listening to the underlying WebSocket and buffering events from the underlying …

CP-1880 Refactor WSocket to fulfill Stream and StreamSink contracts.

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1725
======= w_transport 2.5.0 items =======
CP-1918  - Update changelog for 2.5.0  - https://github.com/Workiva/w_transport/pull/149
CP-1880  - WSocket: StreamSubscription onError, onDone aren't honored  - https://github.com/Workiva/w_transport/pull/142
CP-1884  - Fix Coverage, w_transport  - https://github.com/Workiva/w_transport/pull/146
CP-1862  - Upgrade to sockjs-dart-client 0.3.1  - https://github.com/Workiva/w_transport/pull/145
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.4.0...CP-1725_release_2.5.0
Diff Between Last Tag and New Tag: …

CP-1725 Release w_transport 2.5.0

---

test/integration/ws/common.dart

We are seeing some intermittent failures for the SockJS integration tests on our Travis CI builds.
Increase the delays in the WebSocket integration test suites. This isn't ideal since it increases the build time, but I've created an issue to do a full test audit for performance and optimization: #151.
@jayudey-wf 

CP-1928 Increase WebSocket integration test delays

---

CHANGELOG.md
lib/src/http/http_body.dart
lib/src/http/request_exception.dart
lib/src/http/response_format_exception.dart
lib/w_transport.dart
test/unit/http/http_body_test.dart

_Fixes #131._
#131 
When a response body cannot be properly decoded/encoded using the `Encoding` dictated by the `content-type` header, a `ResponseFormatException` will now be thrown with a much more descriptive message. The content-type, encoding, and body will be included.
@jayudey-wf

CP-1851 Add ResponseFormatException

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1920
======= w_transport 2.5.1 items =======
CP-1851  - Add ResponseFormatException  - https://github.com/Workiva/w_transport/pull/143
CP-1928  - Increase WebSocket integration test delays  - https://github.com/Workiva/w_transport/pull/152
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.5.0...CP-1920_release_2.5.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.5.0...2.5.1

CP-1920 Release w_transport 2.5.1

---

CHANGELOG.md
lib/src/mocks/http.dart
lib/src/mocks/web_socket.dart
lib/w_transport_mock.dart
test/unit/mocks/mock_http_test.dart
test/unit/mocks/mock_web_socket_test.dart

_Fixes #147._
Currently, the mock expectations/handlers require an exact URI match. It would be helpful if we supported matching against `Pattern`s for more flexibility.
- Adds a `MockTransports.http.expectPattern()` method that allows consumers to register an expectation without requiring an exact URI match.
- Adds a `MockTransports.http.whenPattern()` method that allows consumers to register an handler for requests that match the given pattern. The `Match` instance is passed into the handler.
@jayudey-wf 

CP-1885 Add expectPattern(), whenPattern() for partial URI matching in mocks

---

CHANGELOG.md
lib/src/http/common/multipart_request.dart
lib/src/http/common/request.dart
lib/src/http/common/streamed_request.dart
test/integration/http/form_request/suite.dart
test/integration/http/json_request/suite.dart
test/integration/http/plain_text_request/suite.dart
test/integration/http/streamed_request/suite.dart
test/unit/http/form_request_test.dart
test/unit/http/json_request_test.dart
test/unit/http/plain_text_request_test.dart
test/unit/http/streamed_request_test.dart

Currently every request's content-type is set automatically (with the exception of `StreamedRequest`) based on the request type and the encoding. This is too inflexible as there are valid use cases for wanting to override the content-type like integration with a server that expects a certain content-type.
It was requested by @stevenosborne-wf that we add support for manually setting the content-type.
- `FormRequest.contentType`, `JsonRequest.contentType`, and `Request.contentType` can now be set manually.
- `MultipartRequest.contentType` **still cannot** be set manually because a multipart request requires a specific content-type with a boundary string parameter.
- `StreamedRequest.contentType` was already overridable by consumers since the content is not known prior to opening the …

CP-1939 Allow content-type to be set manually

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1940
======= w_transport 2.6.0 items =======
CP-1939  - Allow content-type to be set manually  - https://github.com/Workiva/w_transport/pull/153
CP-1885  - Pattern matching for mock HTTP/WS urls  - https://github.com/Workiva/w_transport/pull/148
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.5.1...CP-1940_release_2.6.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.5.1...2.6.0

CP-1940 Release w_transport 2.6.0

---

lib/src/http/auto_retry.dart
lib/src/http/common/backoff.dart
lib/src/http/common/request.dart
pubspec.yaml
test/naming.dart
test/unit/http/client_test.dart
test/unit/http/common/backoff_test.dart
test/unit/http/request_test.dart
test/unit/platform_independent_unit_test.dart

This is a rebase of https://github.com/Workiva/w_transport/pull/155
For consideration:
We don't currently allow jitter with our exponential backoff strategy.
We now allow the optional inclusion of jitter and a maximum retry duration + default maximum retry duration.
Inspired by https://www.awsarchitectureblog.com/2015/03/backoff.html
**Testing Suggestions:**
run unit-tests
run integration tests
**Required:**
@evanweible-wf @maxwellpeterson-wf @trentgrover-wf @sebastianmalysa-wf 
**FYI:**
@jayudey-wf

cp-1605 : added jitter and maxDuration between retries

---

CHANGELOG.md
lib/src/http/common/form_request.dart
lib/src/http/common/request.dart
lib/src/http/http_body.dart
lib/src/http/response_format_exception.dart
test/unit/http/form_request_test.dart
test/unit/http/http_body_test.dart
test/unit/http/json_request_test.dart
test/unit/http/plain_text_request_test.dart
test/unit/http/response_format_exception_test.dart
test/unit/http/streamed_request_test.dart
test/unit/platform_independent_unit_test.dart

_Fixes #159._
#159 reported an issue when setting a request's content-type manually. If that content-type has no `charset` parameter, and the request's encoding was not set, you will hit an RTE in `HttpBody` when trying to read the body and a conversion is required (bytes->string or vice versa). This is because the `HttpBody` constructors have an optional `fallbackEncoding` parameter that has no default value. For responses, we pass in a fallback encoding of `LATIN1` per RFC 2616, but we aren't passing in a fallback encoding at all for request bodies.
This issue hadn't manifested itself before because most requests set the content-type automatically, including the charset, but #153 introduced the ability to manually set the content-type.
- Update `HttpBody.fromString()` and …

CP-1966 Handle request with no encoding and no charset

---

lib/src/constants.dart
lib/src/http/auto_retry.dart
test/unit/http/backoff_test.dart
test/unit/platform_independent_unit_test.dart

#158 changed `RetryBackOff.duration` to `RetryBackOff.interval` to better describe its purpose, but this is a breaking change.
- Restore the `RetryBackOff.duration` property with a getter that simply returns the value of `RetryBackOff.interval`
- Deprecate `RetryBackOff.duration`
- Add tests to ensure the original behavior works as expected
> A PR to update the changelog will be following shortly and will include a note about this deprecation.
@jayudey-wf 

CP-1974 Restore & deprecate autoRetry.backOff.duration for backwards compatibility

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1954
======= w_transport 2.7.0 items =======
CP-1974  - Restore & deprecate autoRetry.backOff.duration for backwards compatibility  - https://github.com/Workiva/w_transport/pull/163
CP-1975  - Update changelog for 2.7.0  - https://github.com/Workiva/w_transport/pull/164
CP-1966  - Handle request with no encoding and no charset  - https://github.com/Workiva/w_transport/pull/161
CP-1605  - Introduce jitter to exponential backoff  - https://github.com/Workiva/w_transport/pull/158
CP-1963  - Upgrade to dart_style 0.2.4  - https://github.com/Workiva/w_transport/pull/160
Diff Between Last Tag and Proposed Release: …

CP-1954 Release w_transport 2.7.0

---

lib/src/http/common/request.dart
test/integration/http/common_request/browser_test.dart
test/integration/integration_paths.dart
tool/server/handler.dart
tool/server/handlers/test/http/error.dart
tool/server/handlers/test/http/routes.dart

Fix #173 
This will allow auto-retrying of requests that have null responses. Consumers will need to add a `test` method to `request.autoRetry` that checks for a `null` response and returns `true` to enable the functionality.
@evanweible-wf thoughts?
Added an integration test that causes a `null` response and ensures it gets retried.
@evanweible-wf
@jayudey-wf

CP-2059 Support auto-retying requests that fail with a null response

---

test/unit/mocks/mock_http_test.dart

We have tests for the mock handler API, but we weren't exercising all of the standard HTTP methods, nor a custom method. This PR adds two tests to do that.
- Add test to exercise all standard HTTP methods for `MockTransports.http.when()`
- Add test to exercise custom HTTP method for `MockTransports.http.when()`
@jayudey-wf 

CP-2062 Add tests exercising mock handlers for all HTTP methods

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1976
======= w_transport 2.7.1 items =======
CP-2063  - Update changelog for 2.7.1 release  - https://github.com/Workiva/w_transport/pull/181
CP-2062  - Add tests exercising mock handlers for all HTTP methods  - https://github.com/Workiva/w_transport/pull/180
CP-2059  - Support auto-retying requests that fail with a null response  - https://github.com/Workiva/w_transport/pull/176
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.7.0...CP-1976_release_2.7.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.7.0...2.7.1

CP-1976 Release w_transport 2.7.1

---

CHANGELOG.md
lib/src/http/mock/request_mixin.dart
lib/src/mocks/http.dart
lib/src/mocks/web_socket.dart
lib/src/web_socket/mock/w_socket.dart
lib/w_transport_mock.dart
test/unit/mocks/mock_http_test.dart
test/unit/mocks/mock_web_socket_test.dart

_Fixes #167._
Update `when()/whenPattern()` mock methods to return "handler"s that can be canceled at any time. This lets consumers register and unregister mock handlers without having to call `MockTransports.reset()` or `MockTransports.uninstall()` which would be destructive to any mocking that had been set up by other parties.
In other words, this makes it easy for libraries to install mock handlers as necessary and clean up after themselves without affecting other libraries or the application.
- Adds a `MockHttpHandler` class with a `cancel()` method.
- Adds a `MockWebSocketHandler` class with a `cancel()` method.
- `MockTransports.http.when()` returns a `MockHttpHandler` instance.
- `MockTransports.http.whenPattern()` returns a `MockHttpHandler` instance.
- …

CP-2064 Add support for canceling mock handlers

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-2067
======= w_transport 2.8.0 items =======
CP-2064  - Add support for canceling mock handlers  - https://github.com/Workiva/w_transport/pull/170
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.7.1...CP-2067_release_2.8.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.7.1...2.8.0

CP-2067 Release w_transport 2.8.0

---

CHANGELOG.md
lib/src/http/base_request.dart
lib/src/http/common/request.dart
test/unit/http/request_test.dart

_Fixes #187._
An easy way to determine if a request is complete or not has been requested.
- Added `isDone` getter to `BaseRequest`, along with relevant tests.
- _Bonus:_ Found an issue with the implementation of `abort()` - it does not check to see if the request has already been canceled, which makes it vulnerable to a `StateError` being thrown if a consumer called that method more than once. This has been fixed now and a test added.
@jayudey-wf 

CP-2094 Add isDone to BaseRequest

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-2069
======= w_transport 2.9.0 items =======
CP-2096  - Update 2.9.0 release date and notes  - https://github.com/Workiva/w_transport/pull/200
CP-2094  - Add isDone to BaseRequest  - https://github.com/Workiva/w_transport/pull/192
CP-2076  - Increase duration tolerance for jitter tests  - https://github.com/Workiva/w_transport/pull/191
CP-2078  - Update 2.8.0 release date  - https://github.com/Workiva/w_transport/pull/193
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.8.0...CP-2069_release_2.9.0
Diff Between Last Tag and New Tag: …

CP-2069 Release w_transport 2.9.0

---

CHANGELOG.md
lib/src/web_socket/w_socket_subscription.dart
test/integration/ws/common.dart
test/unit/ws/w_socket_subscription_test.dart

_Fixes #171._
In the current implementation of `WSocket`, the subscription to the underlying WebSocket stream is canceled when the subscription to the `WSocket` instance is canceled. This prevents us from receiving the "done" event when the WebSocket connection is closed, which we wait for before considering the `WSocket` instance "done". This means that if a consumer were to cancel their subscription to a `WSocket` instance prior to calling `.close()`, the future returned from the call to `.close()` (as well as the `WSocket.done` future) will never resolve.
```dart
var webSocket = await WSocket.connect(...);
var subscription = webSocket.listen(...);
// ...
subscription.cancel();
await webSocket.close(); // <-- this would never resolve, causing code execution to hang
```
This was reported …

CP-2286 Ensure WSocket always reaches "done" state.

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-2098
======= w_transport 2.9.1 items =======
CP-2286  - Ensure WSocket always reaches "done" state.  - https://github.com/Workiva/w_transport/pull/202
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.0...CP-2098_release_2.9.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.0...2.9.1

CP-2098 Release w_transport 2.9.1

---

CHANGELOG.md
example/http/cross_origin_file_transfer/components/app_component.dart
example/http/cross_origin_file_transfer/components/download_page.dart
example/http/cross_origin_file_transfer/components/drop_zone_component.dart
example/http/cross_origin_file_transfer/components/file_transfer_list_item_component.dart
example/http/cross_origin_file_transfer/components/upload_page.dart
lib/src/http/browser/request_mixin.dart
lib/src/http/common/multipart_request.dart
lib/src/http/common/request.dart
pubspec.yaml
test/integration/http/common_request/suite.dart
test/unit/http/request_test.dart
test/unit/mocks/mock_web_socket_test.dart
test/unit/ws/w_socket_subscription_test.dart

The 1.x line of `http_parser` depended on an older version of the `crypto` package. This is causing some pain for downstream consumers (very slow or sometimes failed `pub get`s).
Newer versions of the `http_parser` package no longer depend on `crypto` and don't have any breaking changes that would be an issue for `w_transport`. We can safely widen our dependency range to include both the 2.x and 3.x lines.
@jayudey-wf 

CP-2425 Widen http_parser dependency range

---

package.json
pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-2375
======= w_transport 2.9.2 items =======
CP-2425  - Widen http_parser dependency range  - https://github.com/Workiva/w_transport/pull/205
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.1...CP-2375_release_2.9.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.1...2.9.2

CP-2375 Release w_transport 2.9.2

---

lib/src/browser_adapter.dart
lib/src/http/browser/http_client.dart
lib/src/http/client.dart
lib/src/http/common/http_client.dart
lib/src/http/http_client.dart
lib/src/http/mock/http_client.dart
lib/src/http/vm/http_client.dart
lib/src/mock_adapter.dart
lib/src/platform_adapter.dart
lib/src/vm_adapter.dart
lib/w_transport.dart
test/integration/http/client/browser_test.dart
test/integration/http/client/mock_test.dart
test/integration/http/client/suite.dart
test/integration/http/client/vm_test.dart
test/integration/platforms/browser_platform_test.dart
test/integration/platforms/mock_platform_test.dart
test/integration/platforms/vm_platform_test.dart
test/unit/http/client_test.dart
test/unit/http/request_test.dart

_Fixes #140._
A `Client` class was recently added to the `dart:html` library, which conflicts with the `Client` class in `w_transport`. This can be worked around, but is annoying.
Deprecate `Client` and add a new `HttpClient` class to replace it. They are identical in functionality. All public APIs still use the deprecated `Client` class to maintain backwards compatibility. `Client` and all references will be removed completely in 4.0.0.
- Deprecate `Client`
- Add `HttpClient`
Docs/changelog will be updated in my docs overhaul WIP branch.
@jayudey-wf 

CP-2243 Rename Client to HttpClient

---

CHANGELOG.md
lib/src/http/common/request.dart
test/unit/http/request_test.dart

If a request exceeds the timeout threshold right after it was canceled, the timeout logic will also attempt to cancel the request, resulting in a `Completer` being completed more than once, which throws a `StateError`.
- Add a check to see if the request has already been canceled in the timeout handler prior to calling `abortRequest()`.
- Add a test to exercise this scenario.
@jayudey-wf 

CP-2615 Prevent StateError when a request times out right after it is canceled

---

pubspec.yaml

* [CP-2615 Prevent StateError when a request times out right after it is canceled](https://github.com/Workiva/w_transport/pull/215)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.2...version-bump-w_transport-2-9-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.2...2.9.3

CP-2426 Release w_transport 2.9.3

---

example/common/global_example_menu_component.dart
example/http/cross_origin_file_transfer/components/drop_zone_component.dart
example/http/cross_origin_file_transfer/services/remote_files.dart
lib/src/http/auto_retry.dart
lib/src/http/browser/multipart_request.dart
lib/src/http/browser/request_mixin.dart
lib/src/http/common/form_request.dart
lib/src/http/common/multipart_request.dart
lib/src/http/common/streamed_request.dart
lib/src/http/http_body.dart
lib/src/http/mock/request_mixin.dart
lib/src/http/mock/response.dart
lib/src/http/response.dart
lib/src/http/response_format_exception.dart
lib/src/http/utils.dart
lib/src/http/vm/http_client.dart
lib/src/http/vm/request_mixin.dart
lib/src/mocks/web_socket.dart
lib/src/web_socket/browser/sockjs.dart
pubspec.yaml
test/integration/http/http_static/suite.dart
test/integration/http/mock_endpoints/custom.dart
test/integration/ws/common.dart
test/unit/http/browser_utils_test.dart
test/unit/http/request_exception_test.dart
test/unit/mocks/mock_response_test.dart
tool/server/handler.dart
tool/server/handlers/example/http/cross_origin_file_transfer_handlers.dart

_Fixes #144._
Now that we've bumped the minimum SDK version, we can leverage null-aware operators.
Update all applicable areas in the example/source/test code where null-aware operators can be used to simplify null-checking logic.
@jayudey-wf 

CP-1883 Use null-aware operators

---

lib/mock.dart
lib/src/http/common/request.dart
lib/src/http/http_client.dart
lib/src/http/mock/base_request.dart
lib/src/http/mock/client.dart
lib/src/http/mock/request_mixin.dart
lib/src/http/mock/requests.dart
lib/src/http/requests.dart
lib/src/mocks/mock_http.dart
lib/src/mocks/mock_transports.dart
lib/src/mocks/mock_web_socket.dart
lib/src/mocks/mock_web_socket_server.dart
lib/src/transport_platform.dart
lib/src/vm_transport_platform.dart
lib/src/web_socket/browser/web_socket.dart
lib/src/web_socket/mock/w_socket.dart
lib/src/web_socket/mock/web_socket.dart
lib/src/web_socket/vm/w_socket.dart
lib/src/web_socket/web_socket.dart
test/integration/http/common_request/mock_test.dart
test/integration/http/mock_endpoints/custom.dart
test/integration/integration_paths.dart
test/integration/platforms/mock_platform_test.dart
test/integration/ws/mock_test.dart
test/unit/http/request_test.dart
test/unit/mocks/mock_http_test.dart
test/unit/mocks/mock_web_socket_test.dart
test/unit/ws/web_socket_test.dart

_Dependent on #222._
This PR addresses a couple of issues with the transport mocks:
- There are several mock classes that were exported publicly that are unnecessary and only serve to add confusion.
- Controlling mock websockets involved creating an instance of `MockWSocket` via the transport mocks. This instance would get returned when an actual `WebSocket` instance was constructed, but it also served as the control point for tests, which is confusing.
- The HTTP mock API stores handlers based on the URI, but it was stripping off the query param to make one of our integration tests easier. This really shouldn't have been the case - `expect()` and `when()` are given an expected URI and that URI should match exactly. Now that we have `expectPattern()` and `whenPattern()`, the original use …

CP-2786 Mock updates

---

lib/src/web_socket/common/web_socket.dart

The `WSocket` is designed and intended to behave like a `Stream` and `StreamSink` at the same time, and as such it should behave just like the builtin Dart classes.
Consider a `StreamController`:
```dart
final sc = new StreamController();
final sub = sc.stream.listen(print);
sc.add(1);
await nextTick();
await sub.cancel();
sc.add(2);
await nextTick();
// OUTPUT:
// 1
```
The first event is added, received, and printed. Then the subscription is canceled, so the second event is added, but not received. The important thing to note, however, is that the stream does not close, since we were able to add the second event without a `StateError` being thrown.
Due to a change I made in this 3.0.0-wip line, `WSocket` does not currently behave like this:
```
// Assume this websocket connection echos …
```

Don't close websocket after subsription is canceled

---

CHANGELOG.md
lib/src/web_socket/common/w_socket.dart
test/integration/ws/common.dart

Currently, `WSocket.cancel()` returns the same `Future` as `WSocket.done`, which means that if you were to wait for cancellation to complete, you would be waiting until the websocket closes.
```dart
final webSocket = await WSocket.connect(...);
final subscription = webSocket.listen((_) { ... });
await subscription.cancel(); // hangs until the websocket closes
```
This is not in line with the behavior that the builtin Dart streams exhibit:
```dart
final sc = new StreamController();
final subscription = sc.stream.listen((_) { .. });
await subscription.cancel(); // completes (doesn't wait for stream to close)
```
- Do not wait for the websocket to close when handling the subscription cancellation.
- **Bonus:** also added a test to ensure that the websocket is not closed just because the …

Dont wait for WebSocket to close when the subscription is canceled

---

pubspec.yaml

* [Dont wait for WebSocket to close when the subscription is canceled](https://github.com/Workiva/w_transport/pull/227)
Requested by: evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.3...version-bump-w_transport-2-9-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.3...2.9.4

CP-2616 Release w_transport 2.9.4

---

pubspec.yaml

* [CP-2430 Minimum sdk 1.14; Upgrade dependencies](https://github.com/Workiva/w_transport/pull/197)
* [CP-2090 Simplify entry point names.](https://github.com/Workiva/w_transport/pull/198)
* [CP-2243 Rename Client to HttpClient](https://github.com/Workiva/w_transport/pull/209)
* [CP-2787 Docs overhaul & v3.0.0 upgrade guide](https://github.com/Workiva/w_transport/pull/210)
* [CP-2611 Rename WebSocket classes](https://github.com/Workiva/w_transport/pull/212)
* [CP-2619 Enable strong mode](https://github.com/Workiva/w_transport/pull/217)
* [CP-2620 Enable Linter](https://github.com/Workiva/w_transport/pull/219)
* [CP-2657 Standardize variable declarations](https://github.com/Workiva/w_transport/pull/220)
* [CP-1883 Use null-aware …

CP-2788 Release w_transport 3.0.0-rc.1

---

lib/src/http/mock/client.dart

In 2.x, the `MockClient` class is exported from the `w_transport_mock.dart` entry point and is not deprecated. In 3.0.0-wip, I deprecated the class, but unknowingly changed the existing constructor signature in a backwards-incompatible way. If consumers are constructing instances of `MockClient`, it would break when upgrading.
The `MockClient` constructor needs to accept a `TransportPlatform` parameter in order for the mock-aware logic to work (which is why I made the change). But, we can make it optional so that existing consumptions still work.
I've tested this with two consumers that were constructing `MockClient()` instances for use in tests, and all tests pass with this fix.
@jayudey-wf 

CP-2820 Restore existing MockClient() constructor

---

pubspec.yaml

* [CP-2820 Restore existing MockClient() constructor](https://github.com/Workiva/w_transport/pull/231)
* [CP-2821 Documentation tweaks](https://github.com/Workiva/w_transport/pull/232)
* [Update tests and increase coverage](https://github.com/Workiva/w_transport/pull/233)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.0-rc.1...version-bump-w_transport-3-0-0-rc-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.0-rc.1...3.0.0-rc.2

CP-2846 Release w_transport 3.0.0-rc.2

---

.travis.yml

Until [this issue with Dart 1.20.1](https://github.com/dart-lang/sdk/issues/27760) is resolved or worked around, we should pin the Dart SDK version to 1.19.1 for our Travis CI runs. This should give us a passing build.
@jayudey-wf 

CP-2909 Pin Dart to 1.19.1 for Travis CI

---

.travis.yml
smithy.yaml

- We needed to add a smithy.yaml for release management to more easily track dependencies.
**Source:**
- Included smithy.yaml
- Included wait for content_shell to be initialized appropriately
**Tests:**
- n/a
- passing CI's
- passing CI
@evanweible-wf

CP-2942 Adding smithy.yaml

---

CHANGELOG.md
lib/src/http/common/request.dart
test/unit/http/request_test.dart

_Fixes #241._
If a request's `autoRetry.test` function is supplied and returns true when the `response` is null, a request that was canceled would erroneously be retried.
Canceling a request now properly makes it ineligible for retry regardless of other factors.

CP-3301 Disallow retry of canceled requests

---

pubspec.yaml

* [CP-3301 Disallow retry of canceled requests](https://github.com/Workiva/w_transport/pull/243)
* [[RED-659] Add Aviary.yaml](https://github.com/Workiva/w_transport/pull/225)
* [CP-2849 Update release date for 3.0.0](https://github.com/Workiva/w_transport/pull/237)
* [CP-2909 Pin Dart to 1.19.1 for Travis CI](https://github.com/Workiva/w_transport/pull/238)
* [CP-2942 Adding smithy.yaml](https://github.com/Workiva/w_transport/pull/239)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.0-rc.2...version-bump-w_transport-3-0-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.0-rc.2...3.0.1

CP-2849 Release w_transport 3.0.1

---

lib/vm.dart

The docs say `show configureWTransportForServer`, but it actually is `configureWTransportForVM`

CP-3328 Fix 'vm.dart' docs

---

.travis.yml
CHANGELOG.md
lib/src/http/common/request.dart
test/unit/http/request_test.dart

Same as #243 but backpatched to the 2.x line.

CP-3323 BACKPATCH Disallow retry of canceled requests

---

pubspec.yaml

* [CP-3323 BACKPATCH Disallow retry of canceled requests](https://github.com/Workiva/w_transport/pull/244)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.4...version-bump-w_transport-2-9-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.4...2.9.5

CP-3299 Release w_transport 2.9.5

---

CHANGELOG.md
lib/src/transport_platform.dart
test/integration/platforms/browser_transport_platform_test.dart
test/integration/platforms/mock_aware_transport_platform.dart

_Fixes #249._
The SockJS params are not being passed through the mock-aware transport platform proxy. It's a corner case that would only have been seen with the following setup:
- MockTransports installed with "fall-through" enabled
- A WebSocket is constructed with the non-SockJS browser transport platform (either directly via the `transportPlatform` parameter or inherited from the globally configured transport platform
- The WebSocket is constructed with SockJS parameters (with the goal of overriding whatever the global configuration may be).
The SockJS params on the `WebSocket` constructor are deprecated and a workaround would be to inject the SockJS-enabled browser transport platform instead.
Pass the SockJS params through the mock-aware proxy.
@Workiva/web-platform-pp 
fyi: …

CP-3434 Pass SockJS params through mock-aware proxy

---

pubspec.yaml

* [CP-3328 Fix 'vm.dart' docs](https://github.com/Workiva/w_transport/pull/247)
* [CP-3434 Pass SockJS params through mock-aware proxy](https://github.com/Workiva/w_transport/pull/250)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.1...version-bump-w_transport-3-0-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.1...3.0.2

Release w_transport 3.0.2

---

CHANGELOG.md
lib/src/http/browser/request_mixin.dart
test/integration/http/common_request/browser_test.dart

If the request is canceled right as we are setting up the underlying XHR instance, attempting to set anything on that XHR instance (like a header or `withCredentials`) will throw this exception:
```
InvalidStateError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.
```
Add `isCanceled` guards in the `BrowserRequestMixin.sendRequestAndFetchResponse()`

CP-3486 Prevent XHR mutation after abort

---

pubspec.yaml
smithy.yaml

* [CP-3486 Prevent XHR mutation after abort](https://github.com/Workiva/w_transport/pull/252)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.5...version-bump-w_transport-2-9-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.5...2.9.6

CP-3502 Release w_transport 2.9.6

---

pubspec.yaml

* [WP-3777 Complete `BaseRequest.done` on cancellation (BACKPATCH)](https://github.com/Workiva/w_transport/pull/256)
Requested by: @maxwellpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.6...version-bump-w_transport-2-9-7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.6...2.9.7

WP-3505 Release w_transport 2.9.7

---

pubspec.yaml

* [cp-3666 : added docs.yml](https://github.com/Workiva/w_transport/pull/255)
* [WP-3778 Complete `BaseRequest.done` on cancellation (3.x)](https://github.com/Workiva/w_transport/pull/257)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.2...version-bump-w_transport-3-0-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.2...3.0.3

WP-3804 Release w_transport 3.0.3

---

docs.yml

Tweaked docs.yaml to match the order and hierarchy of the dev guide
**Docs change only.**

WP-4253 tweak docs.yaml to match guide layout

---

.travis.yml
pubspec.yaml
smithy.yaml
test/integration/ws/common.dart
tool/dev.dart

There were a few tests that started failing after updating to the latest Dart SDK.
Increase some waits to ensure enough time for WS events to occur correctly.

WP-4569 Fix tests on Dart 1.24.x (BACKPATCH 2.X)

---

.travis.yml
pubspec.yaml
smithy.yaml
test/integration/http/common_request/suite.dart
test/integration/platforms/vm_transport_platform_test.dart
test/integration/ws/common.dart
test/integration/ws/sockjs_test.dart
tool/dev.dart

There were a few tests that started failing after updating to the latest Dart SDK.
Increase some waits to ensure enough time for WS events to occur correctly.

WP-4568 Fix tests on Dart 1.24.x

---

pubspec.yaml

* [WP-4421 strong mode 2.x](https://github.com/Workiva/w_transport/pull/264)
* [WP-4569 Fix tests on Dart 1.24.x (BACKPATCH 2.X)](https://github.com/Workiva/w_transport/pull/268)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.7...version-bump-w_transport-2-9-8
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.7...2.9.8

WP-3801 Release w_transport 2.9.8

---

pubspec.yaml

Re-add a stack_trace dependency that was erroneously removed.

Re-add stack_trace dependency

---

pubspec.yaml

* [WP-4629 Re-add stack_trace dependency](https://github.com/Workiva/w_transport/pull/270)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.8...version-bump-w_transport-2-9-9
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.8...2.9.9

Release w_transport 2.9.9

---

pubspec.yaml

* [WP-3986 Fix 3.0.3 changelog header](https://github.com/Workiva/w_transport/pull/261)
* [WP-4253 tweak docs.yaml to match guide layout](https://github.com/Workiva/w_transport/pull/263)
* [WP-4568 Fix tests on Dart 1.24.x](https://github.com/Workiva/w_transport/pull/267)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.3...version-bump-w_transport-3-0-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.3...3.0.4

WP-3805 Release w_transport 3.0.4

---

lib/src/http/common/request.dart
lib/src/mocks/mock_transports.dart
lib/src/mocks/mock_web_socket.dart
lib/src/web_socket/w_socket.dart
pubspec.yaml
test/unit/http/request_test.dart

Fixes #277.
There were a few typing issues that were preventing compatibility with the dart dev compiler.
Fix them!
- Checkout this branch locally
- `pub get`
- in one terminal: `pub serve test --web-compiler=dartdevc`
- in a second terminal: `pub run test -p chrome --pub-serve=8080 test/unit/platform_independent_unit_test.dart`
@Workiva/web-platform-pp 
fyi @valakis

WP-4672 Dart dev compiler compatibility

---

pubspec.yaml

* [WP-4672 Dart dev compiler compatibility](https://github.com/Workiva/w_transport/pull/278)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.5...version-bump-w_transport-3-0-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.5...3.0.6

WP-4685 Release w_transport 3.0.6

---

lib/src/web_socket/browser/sockjs.dart
lib/src/web_socket/browser/w_socket.dart
lib/src/web_socket/global_web_socket_monitor.dart
lib/src/web_socket/vm/w_socket.dart
lib/src/web_socket/w_socket.dart
lib/w_transport.dart
test/integration/browser_integration_test.dart
test/integration/global_web_socket_monitor/browser_test.dart
test/integration/global_web_socket_monitor/common.dart
test/integration/global_web_socket_monitor/sockjs_test.dart
test/integration/global_web_socket_monitor/vm_test.dart
test/integration/vm_integration_test.dart
test/naming.dart

In order to provide some insight into WebSocket connections at a global level, this PR adds a global "event monitor" for WebSocket connections. This monitor can be used to report analytics.
To obtain a WebSocket event monitor:
```dart
var monitor = WSocket.getGlobalEventMonitor();
```
To listen for connection attempt events:
```dart
var monitor = WSocket.getGlobalEventMonitor();
monitor.didAttemptToConnect.listen((event) {
// event.wasSuccessful
// event.url
// event.sockJsProtocolsWhitelist
// event.sockJsSelectedProtocol
});
```

WP-4632 Global WebSocket monitor

---

lib/src/browser_transport_platform.dart
lib/src/browser_transport_platform_with_sockjs.dart
lib/src/global_transport_platform.dart
lib/src/mocks/mock_web_socket_server.dart
lib/src/transport_platform.dart
lib/src/vm_transport_platform.dart
lib/src/web_socket/browser/sockjs.dart
lib/src/web_socket/browser/web_socket.dart
lib/src/web_socket/global_web_socket_monitor.dart
lib/src/web_socket/vm/web_socket.dart
lib/src/web_socket/w_socket.dart
lib/src/web_socket/web_socket.dart
lib/w_transport.dart
test/integration/browser_integration_test.dart
test/integration/global_web_socket_monitor/browser_test.dart
test/integration/global_web_socket_monitor/common.dart
test/integration/global_web_socket_monitor/sockjs_test.dart
test/integration/global_web_socket_monitor/vm_test.dart
test/integration/vm_integration_test.dart
test/naming.dart
test/unit/platform_independent_unit_test.dart
test/unit/ws/global_web_socket_monitor_test.dart

Same as https://github.com/Workiva/w_transport/pull/272, but for the master-line (3.x).

WP-4750 Add a global WebSocket monitor (3.x)

---

pubspec.yaml

* [WP-4674 Address or ignore deprecated uses](https://github.com/Workiva/w_transport/pull/279)
* [WP-4750 Add a global WebSocket monitor (3.x)](https://github.com/Workiva/w_transport/pull/281)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.0.6...version-bump-w_transport-3-1-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.0.6...3.1.0

WP-4686 Release w_transport 3.1.0

---

pubspec.yaml

* [WP-4632 Global WebSocket monitor](https://github.com/Workiva/w_transport/pull/272)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.9.9...version-bump-w_transport-2-10-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.9.9...2.10.0

WP-4630 Release w_transport 2.10.0

---

pubspec.yaml

`pub publish --dry-run` shows this warning:
```
* line 17, column 1 of lib/src/web_socket/global_web_socket_monitor.dart: This package doesn't depend on meta.
import 'package:meta/meta.dart' show required;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Add explicit dependency on the `meta` package.

WP-4759 Add explicit dependency on meta

---

pubspec.yaml

`pub publish --dry-run` shows this warning:
```
* line 3, column 1 of lib/src/web_socket/global_web_socket_monitor.dart: This package doesn't depend on meta.
import 'package:meta/meta.dart' show required;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Add explicit dependency on the `meta` package.

WP-4787 Add explicit dependency on meta (2.x)

---

pubspec.yaml

* [WP-4787 Add explicit dependency on meta (2.x)](https://github.com/Workiva/w_transport/pull/286)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/2.10.0...version-bump-w_transport-2-10-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/2.10.0...2.10.1

WP-4788 WP-4788 Release w_transport 2.10.1

---

pubspec.yaml

* [WP-4759 Add explicit dependency on meta](https://github.com/Workiva/w_transport/pull/284)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.1.0...version-bump-w_transport-3-1-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.1.0...3.1.1

WP-4757 Release w_transport 3.1.1

---

.travis.yml
lib/src/http/common/request.dart
test/integration/platforms/browser_transport_platform_test.dart

When MockTransports are installed with `fallThrough` enabled, we check to see if each request is mock-aware and if it would be handled by an expectation or a mock handler. If it wouldn't be, we switch it to a real request so that it doesn't get stuck (i.e. "fall-through").
Currently, we finalize the request prior to making this check. It turns out that this can have an adverse effect on `MultipartRequests` due to their divergent browser and mock implementations. In the browser, the `MultipartRequest` files map accepts `dart:html.File` and `dart:html.Blob` instances, but those types cannot be imported in any platform other than the browser. As a result, attempting to finalize the mock-aware `MultipartRequest` will fail if either a `File` or `Blob` instance is attached because it does not …

WP-5202 Switch mock-aware requests to real requests before finalizing them

---

pubspec.yaml

* [WP-5202 Switch mock-aware requests to real requests before finalizing them](https://github.com/Workiva/w_transport/pull/290)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.1.1...Workiva:release_w_transport_3_1_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.1.1...3.1.2

WP-4790 Release w_transport 3.1.2

---

pubspec.yaml

There were two dev_dependencies that were unused.
Remove them.

WP-5326 Remove unused dependencies.

---

.travis.yml
pubspec.yaml

Adds `dependency_validator` as a dev dep and runs its check during CI.
@Workiva/web-platform-pp @jacehensley-wf

WP-5472 Add dependency_validator CI check

---

CODEOWNERS

Adds a rule specifically for `aviary.yaml` so that the InfoSec team can make changes to that file on their own if need be.

WP-5637 Add rule for `aviary.yaml` to CODEOWNERS

---

pubspec.yaml

* [WP-5326 Remove unused dependencies.](https://github.com/Workiva/w_transport/pull/292)
* [WP-5472 Add dependency_validator CI check](https://github.com/Workiva/w_transport/pull/293)
* [WP-5627 Add CODEOWNERS file](https://github.com/Workiva/w_transport/pull/294)
* [WP-5637 Add rule for `aviary.yaml` to CODEOWNERS](https://github.com/Workiva/w_transport/pull/295)
* [WP-5258 Automatically use sockjs_client_wrapper if possible.](https://github.com/Workiva/w_transport/pull/296)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.1.2...Workiva:release_w_transport_3_2_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.1.2...3.2.0
The logs for the request that …

WP-5203 Release w_transport 3.2.0

---

pubspec.yaml

Update pubspec to require `sockjs_client_wrapper ^1.0.3` because:
- 1.0.2 fixed overly verbose logging
- 1.0.3 introduced compatibility with DDC & Dart 2
This will ensure that consumers who require the latest w_transport will also get the these fixes without having to depend directly on `sockjs_client_wrapper`.

Require sockjs_client_wrapper ^1.0.3

---

pubspec.yaml

* [WP-6212 Update HttpRequestTypes.md](https://github.com/Workiva/w_transport/pull/301)
* [Require sockjs_client_wrapper ^1.0.3](https://github.com/Workiva/w_transport/pull/304)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.1...Workiva:release_w_transport_3_2_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.1...3.2.2

WP-5854 Release w_transport 3.2.2

---

.gitignore
lib/src/http/browser/multipart_request.dart
test/unit/http/browser/multipart_browser_request_test.dart
test/unit/http/multipart_browser_request_test.dart

FormData was getting added to the request twice.
Don't add it twice.

AF-157 don't add repeated data

---

CHANGELOG.md
pubspec.yaml

* [AF-326 Bump outdated lower bounds](https://github.com/Workiva/w_transport/pull/309)
* [AF-157 don't add repeated data](https://github.com/Workiva/w_transport/pull/310)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.3...Workiva:release_w_transport_3_2_4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.3...3.2.4

Release w_transport 3.2.4

---

CHANGELOG.md
pubspec.yaml

The previous release introduced a new transformer without properly scoping it to the `examples/` directory, resulting in this error for some consumers:
```
Precompiling dependencies...
Loading source assets...
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/w_transport: Error loading transformer "over_react": package "over_react" is not a dependency.
```
Scope the transformer to the `examples/` directory so that it is not also required for consumers of this package.

AF-341 Scope over_react transformer to `examples/`

---

pubspec.yaml

* [AF-341 Scope over_react transformer to `examples/`](https://github.com/Workiva/w_transport/pull/312)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.4...Workiva:release_w_transport_3_2_5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.4...3.2.5

Release w_transport 3.2.5

---

CHANGELOG.md
pubspec.yaml

`sockjs_client_wrapper` v1.0.4 includes an important bug fix, so the minimum is being raised here to ensure consumers get it.

AF-1573 Raise `sockjs_client_wrapper` minimum to 1.0.4

---

pubspec.yaml

* [af_new_drydock_image](https://github.com/Workiva/w_transport/pull/314)
* [AF-1573 Raise `sockjs_client_wrapper` minimum to 1.0.4](https://github.com/Workiva/w_transport/pull/316)
* [AF-1690 Copy content-type/length on mock-aware fall-through](https://github.com/Workiva/w_transport/pull/317)
Requested by: @sebastianmalysa-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.5...Workiva:release_w_transport_3_2_6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.5...3.2.6

AF-345 Release w_transport 3.2.6

---

CHANGELOG.md
pubspec.yaml

* [AF-1711 Update changelog for v3.2.6](https://github.com/Workiva/w_transport/pull/319)
* [update build](https://github.com/Workiva/w_transport/pull/321)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.2.6...Workiva:release_w_transport_3.2.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.2.6...3.2.7

AF-1708 Release w_transport 3.2.7

---

pubspec.yaml

Consume the stable 2.0.0 release of dart_dev.

 AF-2812 Release w_transport 3.2.8

---

tool/server/handlers/example/http/cross_origin_file_transfer_handlers.dart
tool/server/handlers/test/http/upload.dart

An upcoming change to the Dart SDK will change `HttpRequest` and
`HttpClientResponse` from implementing `Stream<List<int>>` to
implementing `Stream<Uint8List>`.
This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.
https://github.com/dart-lang/sdk/issues/36900

Prepare for upcoming change to HttpRequest and HttpClientResponse

---

dart_test.yaml
example/common/global_example_menu.dart
example/http/cross_origin_credentials/client.dart
example/http/cross_origin_file_transfer/client.dart
example/http/simple_client/client.dart
example/index.dart
example/web_socket/echo/client.dart
pubspec.yaml
test/html_test_template.html
test/integration/global_web_socket_monitor/sockjs_wrapper_test.html
test/integration/platforms/browser_transport_platform_test.html
test/integration/ws/sockjs_wrapper_test.html
test/unit/http/utils_test.dart

> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
React 17 was released at the end of October and came with some exciting benefits. For the full list, see the [ReactJS blog post](https://reactjs.org/blog/2020/10/20/react-v17.html).
For Workiva, upgrading so promptly is even more exciting because it:
1. supports our Material-UI (MUI) effort. [MUI will support React 17](https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#500-alpha15) in their next major release. This major is the one that Client Platform will use as the corner stone for the MUI effort. Therefore, to be compatible, Workiva should adopt React 17 as well.
1. helps with the …

Preparations for React 17 compatibility, fix master build

---

lib/src/http/utils.dart
test/unit/http/utils_test.dart

<a href="https://jira.atl.workiva.net/browse/SUPP-49667">[SUPP-49667] IDML not importing to Wdesk - Workiva JIRA</a> investigation was hampered by the fact that some logs were dropped (`Dropped batch that failed to report.` - https://github.com/Workiva/app_intelligence_dart/blob/6a4f67903a8e29daf63a43972fc52e046e9439cf/lib/src/common/reporters/collection_gateway/batched_processor.dart#L144). Those logs (e.g. `index=kinesis-harbour-prod source=app-int* level=warning message="Dropped batch that failed to report." exception.type=*logging*`) seem to be dropped because the response didn't have a proper contentType header (it seems to be just blank).
If the contentType header on a response is empty or whitespace, fall back to the default (octet-stream).
If the contentType header on a response …

Be robust to empty contentType header on response

---

pubspec.yaml

* Major changes:
* [V4: remove `sockjs_client` and some deprecated APIs](https://github.com/Workiva/w_transport/pull/339)
* [DE-690: Delete docs.yml file created for Dev Portal.](https://github.com/Workiva/w_transport/pull/348)
* [Widen Dependency Ranges Blocking Dart 2.13](https://github.com/Workiva/w_transport/pull/351)
* [Raise the Dart SDK minimum to at least 2.11.0](https://github.com/Workiva/w_transport/pull/354)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/3.3.1...Workiva:release_w_transport_4.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/3.3.1...4.0.0
The logs for the request that created this PR can be found …

RM-109516 Release w_transport 4.0.0

---

CHANGELOG.md
lib/src/mocks/mock_http.dart
lib/src/mocks/mock_transports.dart
pubspec.yaml
test/unit/mocks/mock_http_test.dart

We currently store pattern matching mock http request handlers in a `Map<Pattern, Map<String /* method */, PatternRequestHandler>>`. The key can be a RegExp. Two equivalent RegExp are not identical. Here's a quick example to demonstrate how this behaves:
```dart
void main() {
final keyA = RegExp(r'https://fake.com/a/([bc]+)/d');
final keyB = RegExp(r'https://fake.com/a/([bc]+)/d');
final myMap = <Pattern, int>{};
myMap[keyA] = 0;
myMap[keyB] = 1;
print(myMap.keys.length); // 2
print(keyA == keyB); // false
}
```
This is usually OK. We run into an issue though if the consumer registers a pattern once, cancels it, and then registers it a second time with a newly constructed RegExp. In that case the previous pattern is still in the handler map, but it's value is an empty map of handlers. …

CPLAT-16481: Improve storage of pattern-matched mock HTTP request handlers

---

CHANGELOG.md
lib/src/http/http_body.dart
lib/src/http/response.dart

On the VM, JSON responses that do not specify a charset are decoded using latin1/ISO-8859-1. The fallback to latin1 is obsolete behavior, and we should now fall back to the default for the media type. For JSON this is utf-8. On the web, this already behaves correctly, so this should improve consistentency. 
Hard-code the asJson method on HttpBody to decode as utf-8 from bytes, rather than from string.
[contributing-manual-testing]: …

Fix JSON decoding when charset isn't specified on VM to use UTF-8

---

CHANGELOG.md
pubspec.yaml

Widening `http_parser` will allow downstream resolution to newer versions of other packages.
- Widen `fluri` and `http_parser` dependency ranges
- Both major versions are null-safe migrations only and should otherwise be backwards compat.

FEA-900: Widen ranges on `fluri` and `http_parser`

---

pubspec.yaml

* [Update references to the previous team name](https://github.com/Workiva/w_transport/pull/378)
* [FEA-900: Widen ranges on `fluri` and `http_parser`](https://github.com/Workiva/w_transport/pull/379)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/4.1.3...Workiva:release_w_transport_4.1.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/4.1.3...4.1.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_ …

RM-156336 Release w_transport 4.1.4

---

CHANGELOG.md
docs/guides/HttpSendRequestReceiveResponseHandleFailure.md
lib/src/http/request_dispatchers.dart

We've had a few instances where downloading binary files with w_transport's `.get()` method leads to a confusing encoding error. This can typically be solved either by having the server set the correct encoding in the content-type header, or by using `.streamGet()` and reading the response with `body.asBytes()` to avoid encoding altogether. Suggest the latter approach in our documentation.

FEA-1542: Suggest using `.streamGet()` for binary responses

---

example/pubspec.yaml

This PR widens the allowable version ranges of dart_dev so that all repos at Workiva can consume dart_dev 4.0.0 without updating all repositories in lock step.
For more info, reach out to Timothy Steward or `#link23-state-of-the-dart-jam` on Slack.
[_Created by Sourcegraph batch change `Workiva/dart_dev_widen_ranges_v4`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/dart_dev_widen_ranges_v4)

Prepare for dart_dev v4.0.0

---

CHANGELOG.md
lib/src/http/common/request.dart

When using `MockTransports.install(fallThrough: true)`, each request (when `.send()` is called) is checked against the mocks configured at that time. If no matching mocks are found, the request "falls through" and is converted to a real request. The `send()` method has an optional `body` parameter that is lost in this specific corner case - when the request is converted to a real request, the `body` parameter is not being passed on.
Forward on the `body` parameter after switching to a real request.

FEA-1797: Bug fix for the `send` method's `body` param on fall through requests

---

pubspec.yaml

* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/w_transport/pull/384)
* [Pin mockito 5](https://github.com/Workiva/w_transport/pull/387)
* [FEA-1542: Suggest using `.streamGet()` for binary responses](https://github.com/Workiva/w_transport/pull/388)
* [FEA-1543: Run CI on newer Dart SDK versions](https://github.com/Workiva/w_transport/pull/389)
* [Prepare for dart_dev v4.0.0](https://github.com/Workiva/w_transport/pull/391)
* [FEA-1797: Bug fix for the `send` method's `body` param on fall through requests](https://github.com/Workiva/w_transport/pull/393)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/4.1.5...Workiva:release_w_transport_4.1.6
Diff …

RM-167470 Release w_transport 4.1.6

---

CHANGELOG.md
lib/src/http/request_exception.dart
pubspec.yaml
test/unit/http/request_test.dart

A runtime error was uncovered when testing the 5.0.0 release more.
The collection dependency minimum was on a pre-release version.
Make RequestException.request nullable too
Use `collection: ^1.15.0` instead of `^1.15.0-nullsafety.4`

Nullable fixes

---

lib/src/http/base_request.dart
lib/src/http/client.dart
lib/src/http/common/http_client.dart
lib/src/http/common/request.dart
lib/w_transport.dart
test/integration/http/common_request/suite.dart

Having an unbounded request is rarely desirable and has caused issues with too many open, long-running connections.
Set a (customizable) default timeout.
A new `defaultTimeoutThreshold` setter allows all requests without an explicit timeout to inherit that default.

FEA-2422: Allow setting a default timeout for all requests

---

pubspec.yaml

* Minor changes:
* [FEA-2422: Allow setting a default timeout for all requests](https://github.com/Workiva/w_transport/pull/390)
* [Add changelog entry for 5.1.0](https://github.com/Workiva/w_transport/pull/408)
Requested by: @corwinweber-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.0.1...Workiva:release_w_transport_5.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.0.1...5.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/60593041495 …

RM-208849 Release w_transport 5.1.0

---

example/pubspec.yaml
pubspec.yaml

Summary
---
Frontend Frameworks is updating dependencies! Now that we can resolve to analyzer 2
we can raise the minimums of many dependencies were ranged to support both 
analyzer 1 and 2.
```
pubspec_codemod raise-min analyzer 2.0.0 --recursive
pubspec_codemod raise-min dependency_validator 3.0.0 --recursive
pubspec_codemod raise-min test_html_builder 3.0.0 --recursive
pubspec_codemod raise-min dart_style 2.0.0 --recursive
pubspec_codemod raise-min build_web_compilers 3.0.0 --recursive
pubspec_codemod raise-min build_test 2.0.0 --recursive
pubspec_codemod raise-min build_runner 2.0.0 --recursive
pubspec_codemod raise-min w_common 3.0.0 --recursive
pubspec_codemod raise-min w_common_tools 3.0.0 --recursive
pubspec_codemod raise-min uuid 3.0.0 --recursive
pubspec_codemod raise-min fluri …
```

Update dev dependencies for analyzer 2

---

CHANGELOG.md
example/pubspec.yaml
lib/src/web_socket/browser/sockjs_wrapper.dart
lib/src/web_socket/global_web_socket_monitor.dart
pubspec.yaml
test/integration/global_web_socket_monitor/sockjs_common.dart
test/integration/global_web_socket_monitor/sockjs_wrapper_test.dart
test/integration/global_web_socket_monitor/sockjs_wrapper_test.html
test/integration/ws/sockjs_wrapper_test.html

We need a way to pipe the websocket debug url to consumers
* Add `debugUrl` to `WebSocketConnectEvent` which is emitted via the
`GlobalWebSocketMonitor`. When using SockJS, this will be populated with the
full URL that the underlying transport is using, which can be useful information
for debugging.

FEA-2879: Include SockJS debug URL

---

pubspec.yaml

* [Update dev dependencies for analyzer 2](https://github.com/Workiva/w_transport/pull/409)
* [Dart 2.19](https://github.com/Workiva/w_transport/pull/414)
* [FEA-2879: Include SockJS debug URL](https://github.com/Workiva/w_transport/pull/415)
Requested by: @corwinweber-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.1.0...Workiva:release_w_transport_5.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.1.0...5.1.1
This pull request can be recreated by clicking …

RM-211054 Release w_transport 5.1.1

---

pubspec.yaml

Requested by: @corwinweber-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.1.1...Workiva:release_w_transport_5.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.1.1...5.2.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=417)

RM-222302 Release w_transport 5.2.0

---

example/pubspec.yaml

This PR widens the allowable version ranges to over_react 5.0.0 / over_react_test 3.0.0 so that all repos at Workiva can consume without updating all repositories in lock step.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - and **have already been tested and verified as safe for consumption** using the `w_transport` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
---
For more information about these changes, see [this …

Allow consumption of null-safe over_react and over_react_test versions

---

example/pubspec.yaml

This PR sets the lower bound of over_react to `^5.0.0` and over_react_test to `^3.0.0` so that all repos at Workiva 
are consuming the null-safe versions of these packages.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - 
and **have already been tested and verified as safe for consumption** using the 
`w_transport` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to 
releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
For more information about these changes, see [this …

Consume null-safe over_react v5 and over_react_test v3

---

pubspec.yaml

* [FEA-3269: Fixed CI and addressed NNBD errors](https://github.com/Workiva/w_transport/pull/421)
* [Allow consumption of null-safe over_react and over_react_test versions](https://github.com/Workiva/w_transport/pull/422)
* [Consume null-safe over_react v5 and over_react_test v3](https://github.com/Workiva/w_transport/pull/423)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.2.0...Workiva:release_w_transport_5.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.2.0...5.2.1
This pull …

RM-222341 Release w_transport 5.2.1

---

example/pubspec.yaml
pubspec.yaml

This PR raises the max version of build_web_compilers to 5.0.0 to prep for Dart 3. 
Since we're all on Dart 2.19 right now, no pub resolution will change as we can't
actually resolve to build_web_compilers 4+ without Dart 3.
Passing CI should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `$support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/build_web_compilers_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/build_web_compilers_raise_max_v5_0_0)

Raise the build_web_compilers dependency max to v5.0.0

---

_test_server/pubspec.yaml
pubspec.yaml

For Dart packages that have migrated to null safety (full or partial)
we can raise the minimum Dart SDK version to 2.19.0 instead of 2.12.0.
This will allow us to take advantage of new language features as soon as
files are migrated to null safety. We've shown that unmigrated consumers
do not have issues consuming packages with a higher minimum Dart SDK version.
- Raise minimum Dart SDK version to 2.19.0
[_Created by Sourcegraph batch change `Workiva/raise_min_dart_sdk_2_19`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/raise_min_dart_sdk_2_19)

raise_min_dart_sdk_2_19

---

pubspec.yaml

* [DSC-10121 - Complete transition to GHA](https://github.com/Workiva/w_transport/pull/425)
* [Replace mockito with mocktail](https://github.com/Workiva/w_transport/pull/427)
* [Workiva Analysis Options v2](https://github.com/Workiva/w_transport/pull/428)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/w_transport/pull/429)
* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/w_transport/pull/430)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/w_transport/pull/432)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.2.1...Workiva:release_w_transport_5.2.2
Diff Between Last Tag and New Tag: …

RM-251053 Release w_transport 5.2.2

---

lib/src/http/response_format_exception.dart
test/unit/http/http_body_test.dart
test/unit/http/response_format_exception_test.dart

The `toString()` of a `ResponseFormatException` produces a message that contains the contents of the response. This is far too easy for a logging system to dump information that should not be in the logs.
Stop including the body in the ResponseFormatException

ESG-11074 Don't log bytes / body in the error message

---

pubspec.yaml

* [ESG-11074 Don't log bytes / body in the error message](https://github.com/Workiva/w_transport/pull/434)
Requested by: @regenvanwalbeek-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.2.2...Workiva:release_w_transport_5.2.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.2.2...5.2.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=436)

RM-302024 Release w_transport 5.2.3

---

_test_server/pubspec.yaml
example/pubspec.yaml
pubspec.yaml

This PR raises the max version of uuid to 5.0.0. Passing CI
should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/uuid_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/uuid_raise_max_v5_0_0)

Raise the uuid dependency max to v5.0.0

---

_test_server/pubspec.yaml
example/pubspec.yaml
pubspec.yaml

This PR raises the min version of uuid to 4.0.0. Passing CI
should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/uuid_raise_min_v4_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/uuid_raise_min_v4_0_0)

Raise the uuid dependency min to v4.0.0

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
lib/src/http/http_interceptor.dart
lib/src/web_socket/web_socket.dart

An entrypoint import can be defined as an import within `lib/src` that imports a file within `lib/*.dart` (the entrypoints of a dart package). These imports are always unnecessary, and can contribute to slower dart build performance.
This PR naively removes every entrypoint import within the repo, and updates the `gha-dart/.../checks.yaml` to the latest version. In order to merge this PR a few manual changes must be performed:
- Navigate to every file which has analysis errors caused from the missing import. Rely on intellisense to import the necessary symbol from the specific file, not the entrypoint import
- Implement the `no_entrypoint_imports` additional-checks option in `gha-dart@v2.10.13` that was added in [this PR](https://github.com/Workiva/gha-dart/pull/716). This will prevent …

FEDX-3766: no_entrypoint_imports

---

CHANGELOG.md
lib/src/http/browser/utils.dart

We're seeing late initialization errors [here](https://github.com/Workiva/w_transport/blob/master/lib/src/http/browser/utils.dart#L37). 
It seems that pause can get called and execute onPause before onListen executes
Updated this to be a bit safer and to align more closely with the [Dart-sdk example of how to do a stream transform. ](https://github.com/dart-lang/sdk/blob/2.19.6/sdk/lib/async/stream.dart#L2348-L2381)
This will fix the late init error. 
* CI passes

FEA-8530: Fix late init error

---

CHANGELOG.md
pubspec.yaml

* [FEA-8530: Fix late init error](https://github.com/Workiva/w_transport/pull/449)
Requested by: @corwinweber-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_transport/compare/5.4.0...Workiva:release_w_transport_5.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_transport/compare/5.4.0...5.4.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6059304149581824/?repo_name=Workiva%2Fw_transport&pull_number=450)

RM-349935 Release w_transport 5.4.1
